# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4Y1dLDpcBU7Lo_eTTmmNtdH27ckpylB
"""

import streamlit as st
import random

# -----------------------------
# Page configuration
# -----------------------------
st.set_page_config(
    page_title="Fraction Fun Game",
    page_icon="🍕",
    layout="centered"
)

# -----------------------------
# Initialize game
# -----------------------------
if "question" not in st.session_state:
    st.session_state.question = 0
    st.session_state.score = 0
    st.session_state.answer_checked = False
    st.session_state.selected_answer = None
    st.session_state.finished = False

# -----------------------------
# Fraction questions
# -----------------------------
questions = [
    {
        "question": "A pizza is divided into 2 equal parts. One part is shaded. What fraction is shaded?",
        "visual": "🟩⬜",
        "options": ["1/2", "1/3", "2/1", "1/4"],
        "answer": "1/2"
    },
    {
        "question": "A cake is divided into 4 equal parts. One part is shaded. What fraction is shaded?",
        "visual": "🟩⬜⬜⬜",
        "options": ["1/2", "1/4", "2/4", "3/4"],
        "answer": "1/4"
    },
    {
        "question": "There are 3 equal parts. Two are shaded. What fraction is shaded?",
        "visual": "🟩🟩⬜",
        "options": ["1/3", "2/3", "2/2", "3/2"],
        "answer": "2/3"
    },
    {
        "question": "A chocolate bar has 4 equal pieces. Three are shaded. What fraction is shaded?",
        "visual": "🟫🟫🟫⬜",
        "options": ["1/4", "2/4", "3/4", "4/3"],
        "answer": "3/4"
    },
    {
        "question": "A fruit basket has 5 equal sections. Two sections contain mangoes. What fraction is mango?",
        "visual": "🥭🥭⬜⬜⬜",
        "options": ["2/5", "3/5", "1/5", "5/2"],
        "answer": "2/5"
    },
    {
        "question": "A rectangle is divided into 3 equal parts. One part is shaded. What fraction is shaded?",
        "visual": "🟦⬜⬜",
        "options": ["1/2", "1/3", "2/3", "3/1"],
        "answer": "1/3"
    },
    {
        "question": "A watermelon is divided into 4 equal pieces. Two pieces are eaten. What fraction was eaten?",
        "visual": "🍉🍉⬜⬜",
        "options": ["1/4", "2/4", "3/4", "4/2"],
        "answer": "2/4"
    },
    {
        "question": "There are 6 equal pieces of fruit. One piece is an orange. What fraction is orange?",
        "visual": "🍊⬜⬜⬜⬜⬜",
        "options": ["1/6", "2/6", "1/5", "6/1"],
        "answer": "1/6"
    },
    {
        "question": "A garden has 5 equal sections. Four sections have flowers. What fraction has flowers?",
        "visual": "🌸🌸🌸🌸⬜",
        "options": ["1/5", "2/5", "4/5", "5/4"],
        "answer": "4/5"
    },
    {
        "question": "A box has 4 equal parts. All 4 parts are filled. What fraction is filled?",
        "visual": "🟨🟨🟨🟨",
        "options": ["1/4", "2/4", "3/4", "4/4"],
        "answer": "4/4"
    }
]

# -----------------------------
# Header
# -----------------------------
st.title("🍕 Fraction Fun Game")
st.subheader("🎮 Easy Level")

st.write(
    "Look at the picture, think about the shaded parts, "
    "and choose the correct fraction!"
)

# -----------------------------
# Game finished
# -----------------------------
if st.session_state.question >= len(questions):

    st.session_state.finished = True

    st.success("🎉 Game Complete!")

    st.markdown(
        f"# ⭐ Your Score: "
        f"{st.session_state.score}/{len(questions)}"
    )

    percentage = (
        st.session_state.score / len(questions) * 100
    )

    if percentage >= 80:
        st.balloons()
        st.success("🏆 Excellent! You are a Fraction Champion!")
    elif percentage >= 60:
        st.info("👏 Good job! Keep practicing fractions!")
    else:
        st.warning("💪 Keep practicing. You can do it!")

    if st.button("🔄 Play Again", use_container_width=True):

        st.session_state.question = 0
        st.session_state.score = 0
        st.session_state.answer_checked = False
        st.session_state.selected_answer = None
        st.session_state.finished = False

        st.rerun()

else:

    # -----------------------------
    # Current question
    # -----------------------------
    q = questions[st.session_state.question]

    progress = (
        st.session_state.question /
        len(questions)
    )

    st.progress(progress)

    st.write(
        f"### Question "
        f"{st.session_state.question + 1} "
        f"of {len(questions)}"
    )

    # Visual
    st.markdown(
        f"<div style='text-align:center; "
        f"font-size:55px; padding:20px;'>"
        f"{q['visual']}"
        f"</div>",
        unsafe_allow_html=True
    )

    # Question
    st.markdown(
        f"### {q['question']}"
    )

    # -----------------------------
    # Answer buttons
    # -----------------------------
    for option in q["options"]:

        if st.button(
            option,
            key=f"{st.session_state.question}_{option}",
            use_container_width=True
        ):

            if not st.session_state.answer_checked:

                st.session_state.selected_answer = option
                st.session_state.answer_checked = True

                if option == q["answer"]:
                    st.session_state.score += 1

                st.rerun()

    # -----------------------------
    # Feedback
    # -----------------------------
    if st.session_state.answer_checked:

        if st.session_state.selected_answer == q["answer"]:

            st.success(
                "✅ Correct! Great job!"
            )

        else:

            st.error(
                f"❌ Not quite. "
                f"The correct answer is **{q['answer']}**."
            )

        st.write(
            f"⭐ Score: "
            f"{st.session_state.score}"
        )

        # Next question
        if st.button(
            "➡️ Next Question",
            use_container_width=True
        ):

            st.session_state.question += 1
            st.session_state.answer_checked = False
            st.session_state.selected_answer = None

            st.rerun()

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:

    st.header("📚 How to Play")

    st.write("1️⃣ Look at the picture.")
    st.write("2️⃣ Count the equal parts.")
    st.write("3️⃣ Count the shaded parts.")
    st.write("4️⃣ Choose the fraction.")
    st.write("5️⃣ Check your answer!")

    st.divider()

    st.write(
        "💡 Remember:"
    )

    st.write(
        "**Numerator** = shaded parts"
    )

    st.write(
        "**Denominator** = total equal parts"
    )