# -*- coding: utf-8 -*-
"""GAME MULTIPLICACAO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnoxhPs0l5uMBY3R0FXceyHUpbAQCgf9
"""

Absolutely. Below is a **complete, ready-to-deploy Streamlit game** for Grade 1 multiplication. It uses 10 questions, 4 choices, three difficulty levels, rural farming contexts, emojis, score/progress tracking, immediate feedback, and a Play Again button.

### `app.py`

```python
import streamlit as st
import random

# ---------------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="🌱 Multiplication Farm Adventure",
    page_icon="🥭",
    layout="centered"
)

# ---------------------------------------------------------
# CUSTOM CSS
# ---------------------------------------------------------
st.markdown("""
<style>
    .main {
        background: linear-gradient(180deg, #FFF8DC 0%, #E8F5E9 100%);
    }

    .title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        color: #2E7D32;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #5D4037;
        margin-bottom: 20px;
    }

    .question-box {
        background-color: white;
        padding: 25px;
        border-radius: 20px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.12);
        margin: 20px 0;
        text-align: center;
    }

    .question {
        font-size: 30px;
        font-weight: bold;
        color: #333333;
    }

    .difficulty {
        font-size: 18px;
        font-weight: bold;
    }

    .score-box {
        background-color: #FFF3CD;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
        color: #6D4C41;
    }

    .feedback {
        padding: 15px;
        border-radius: 15px;
        font-size: 20px;
        text-align: center;
        font-weight: bold;
    }

    div.stButton > button {
        border-radius: 15px;
        font-size: 18px;
        font-weight: bold;
        min-height: 50px;
    }
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------
# QUESTIONS
# ---------------------------------------------------------
QUESTIONS = [
    # EASY
    {
        "question": "🥭 There are 2 baskets. Each basket has 2 mangoes. How many mangoes are there?",
        "choices": ["2", "4", "6", "8"],
        "answer": "4",
        "difficulty": "Easy 🌱",
        "explanation": "2 groups of 2 = 2 × 2 = 4 mangoes!"
    },
    {
        "question": "🌱 A farmer plants 3 rows. Each row has 2 plants. How many plants are there?",
        "choices": ["5", "6", "7", "8"],
        "answer": "6",
        "difficulty": "Easy 🌱",
        "explanation": "3 groups of 2 = 3 × 2 = 6 plants!"
    },
    {
        "question": "🥭 There are 4 mango trees. Each tree has 2 mangoes. How many mangoes?",
        "choices": ["6", "8", "10", "12"],
        "answer": "8",
        "difficulty": "Easy 🌱",
        "explanation": "4 × 2 = 8 mangoes!"
    },

    # MEDIUM
    {
        "question": "🌽 A farmer has 3 baskets. Each basket has 4 ears of corn. How many ears of corn?",
        "choices": ["7", "10", "12", "14"],
        "answer": "12",
        "difficulty": "Medium 🌿",
        "explanation": "3 groups of 4 = 3 × 4 = 12 ears of corn!"
    },
    {
        "question": "🥭 There are 5 mango trees. Each tree has 3 mangoes. How many mangoes?",
        "choices": ["10", "12", "15", "18"],
        "answer": "15",
        "difficulty": "Medium 🌿",
        "explanation": "5 × 3 = 15 mangoes!"
    },
    {
        "question": "🌱 A farmer plants 4 rows. Each row has 5 plants. How many plants?",
        "choices": ["15", "20", "25", "30"],
        "answer": "20",
        "difficulty": "Medium 🌿",
        "explanation": "4 × 5 = 20 plants!"
    },
    {
        "question": "🐔 There are 6 chickens. Each chicken has 2 chicks. How many chicks?",
        "choices": ["8", "10", "12", "14"],
        "answer": "12",
        "difficulty": "Medium 🌿",
        "explanation": "6 × 2 = 12 chicks!"
    },

    # DIFFICULT
    {
        "question": "🥭 A farmer picks 6 mangoes from each of 4 trees. How many mangoes?",
        "choices": ["20", "22", "24", "26"],
        "answer": "24",
        "difficulty": "Difficult 🌳",
        "explanation": "6 × 4 = 24 mangoes!"
    },
    {
        "question": "🌾 There are 5 rows of rice. Each row has 6 plants. How many rice plants?",
        "choices": ["25", "30", "35", "36"],
        "answer": "30",
        "difficulty": "Difficult 🌳",
        "explanation": "5 × 6 = 30 rice plants!"
    },
    {
        "question": "🥥 A farmer has 4 coconut trees. Each tree has 7 coconuts. How many coconuts?",
        "choices": ["21", "24", "28", "32"],
        "answer": "28",
        "difficulty": "Difficult 🌳",
        "explanation": "4 × 7 = 28 coconuts!"
    }
]


# ---------------------------------------------------------
# SESSION STATE
# ---------------------------------------------------------
if "questions" not in st.session_state:
    st.session_state.questions = random.sample(QUESTIONS, 10)

if "current_question" not in st.session_state:
    st.session_state.current_question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected_answer" not in st.session_state:
    st.session_state.selected_answer = None

if "game_finished" not in st.session_state:
    st.session_state.game_finished = False


# ---------------------------------------------------------
# TITLE
# ---------------------------------------------------------
st.markdown(
    '<div class="title">🥭🌱 Multiplication Farm Adventure 🌱🥭</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🚜 Help the farmer solve multiplication problems!</div>',
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# GAME FINISHED
# ---------------------------------------------------------
if st.session_state.game_finished:

    st.balloons()

    score = st.session_state.score

    st.markdown("## 🎉 Farm Adventure Complete! 🎉")

    st.markdown(
        f"""
        <div class="score-box">
            🏆 Your Score: {score} / 10
        </div>
        """,
        unsafe_allow_html=True
    )

    percentage = score * 10

    if percentage == 100:
        st.success("🌟 AMAZING! You are a Super Multiplication Farmer! 🥭🏆")
    elif percentage >= 80:
        st.success("🎉 Excellent work! Your farm is growing beautifully! 🌱")
    elif percentage >= 60:
        st.info("😊 Good job! Keep practicing multiplication!")
    else:
        st.warning("💪 Nice try! Let's practice some more multiplication!")

    st.markdown("### 🌾 You helped the farmer today!")

    if st.button("🔄 Play Again", use_container_width=True):
        st.session_state.questions = random.sample(QUESTIONS, 10)
        st.session_state.current_question = 0
        st.session_state.score = 0
        st.session_state.answered = False
        st.session_state.selected_answer = None
        st.session_state.game_finished = False
        st.rerun()

    st.stop()


# ---------------------------------------------------------
# CURRENT QUESTION
# ---------------------------------------------------------
question_number = st.session_state.current_question + 1
total_questions = len(st.session_state.questions)

current = st.session_state.questions[
    st.session_state.current_question
]

# ---------------------------------------------------------
# SCORE
# ---------------------------------------------------------
st.markdown(
    f"""
    <div class="score-box">
        🏆 Score: {st.session_state.score} / {total_questions}
    </div>
    """,
    unsafe_allow_html=True
)

st.write("")

# ---------------------------------------------------------
# PROGRESS
# ---------------------------------------------------------
st.write(f"🌱 Question {question_number} of {total_questions}")

progress = st.session_state.current_question / total_questions
st.progress(progress)

# ---------------------------------------------------------
# DIFFICULTY
# ---------------------------------------------------------
st.markdown(
    f"""
    <div style="text-align:center;">
        <span class="difficulty">
            {current["difficulty"]}
        </span>
    </div>
    """,
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# QUESTION
# ---------------------------------------------------------
st.markdown(
    f"""
    <div class="question-box">
        <div class="question">
            {current["question"]}
        </div>
    </div>
    """,
    unsafe_allow_html=True
)


# ---------------------------------------------------------
# ANSWER BUTTONS
# ---------------------------------------------------------
if not st.session_state.answered:

    st.write("### 👇 Choose your answer:")

    for i, choice in enumerate(current["choices"]):

        if st.button(
            f"🔵 {choice}",
            key=f"answer_{question_number}_{i}",
            use_container_width=True
        ):

            st.session_state.selected_answer = choice
            st.session_state.answered = True

            if choice == current["answer"]:
                st.session_state.score += 1

            st.rerun()


# ---------------------------------------------------------
# IMMEDIATE FEEDBACK
# ---------------------------------------------------------
else:

    selected = st.session_state.selected_answer

    if selected == current["answer"]:

        st.markdown(
            """
            <div class="feedback"
                 style="background-color:#DFF0D8;color:#2E7D32;">
                🎉 Correct! Great job! 🌟
            </div>
            """,
            unsafe_allow_html=True
        )

        st.write(f"💡 {current['explanation']}")

    else:

        st.markdown(
            """
            <div class="feedback"
                 style="background-color:#F8D7DA;color:#B71C1C;">
                😊 Not quite! Let's learn from it!
            </div>
            """,
            unsafe_allow_html=True
        )

        st.write(
            f"✅ The correct answer is **{current['answer']}**."
        )

        st.write(f"💡 {current['explanation']}")

    st.write("")

    # -----------------------------------------------------
    # NEXT QUESTION
    # -----------------------------------------------------
    if question_number < total_questions:

        if st.button(
            "➡️ Next Question",
            use_container_width=True
        ):
            st.session_state.current_question += 1
            st.session_state.answered = False
            st.session_state.selected_answer = None
            st.rerun()

    else:

        if st.button(
            "🏆 See My Result",
            use_container_width=True
        ):
            st.session_state.game_finished = True
            st.rerun()


# ---------------------------------------------------------
# FOOTER
# ---------------------------------------------------------
st.write("")
st.markdown(
    """
    <div style="text-align:center;color:#795548;">
        🚜 Keep learning • 🌱 Keep growing • 🥭 Keep multiplying!
    </div>
    """,
    unsafe_allow_html=True
)
```

### How to run it

Create a folder such as:

```text
multiplication-farm-game/
│
├── app.py
└── requirements.txt
```

Put this in `requirements.txt`:

```text
streamlit
```

### Run on your computer

Install Streamlit:

```bash
pip install streamlit
```

Then:

```bash
streamlit run app.py
```

The game will open in your browser.

### Deploy to Streamlit Community Cloud

1. Create a GitHub repository.
2. Upload:

   * `app.py`
   * `requirements.txt`
3. Go to **Streamlit Community Cloud**.
4. Select **Create app**.
5. Select your GitHub repository.
6. Choose `app.py` as the main file.
7. Click **Deploy**.

The game is designed to use only standard Python + Streamlit, so there are **no extra packages or APIs** required.

Absolutely. Below is a **complete, ready-to-deploy Streamlit game** for Grade 1 multiplication. It uses 10 questions, 4 choices, three difficulty levels, rural farming contexts, emojis, score/progress tracking, immediate feedback, and a Play Again button.

### `app.py`

```python
import streamlit as st
import random

# ---------------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="🌱 Multiplication Farm Adventure",
    page_icon="🥭",
    layout="centered"
)

# ---------------------------------------------------------
# CUSTOM CSS
# ---------------------------------------------------------
st.markdown("""
<style>
    .main {
        background: linear-gradient(180deg, #FFF8DC 0%, #E8F5E9 100%);
    }

    .title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        color: #2E7D32;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #5D4037;
        margin-bottom: 20px;
    }

    .question-box {
        background-color: white;
        padding: 25px;
        border-radius: 20px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.12);
        margin: 20px 0;
        text-align: center;
    }

    .question {
        font-size: 30px;
        font-weight: bold;
        color: #333333;
    }

    .difficulty {
        font-size: 18px;
        font-weight: bold;
    }

    .score-box {
        background-color: #FFF3CD;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
        color: #6D4C41;
    }

    .feedback {
        padding: 15px;
        border-radius: 15px;
        font-size: 20px;
        text-align: center;
        font-weight: bold;
    }

    div.stButton > button {
        border-radius: 15px;
        font-size: 18px;
        font-weight: bold;
        min-height: 50px;
    }
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------
# QUESTIONS
# ---------------------------------------------------------
QUESTIONS = [
    # EASY
    {
        "question": "🥭 There are 2 baskets. Each basket has 2 mangoes. How many mangoes are there?",
        "choices": ["2", "4", "6", "8"],
        "answer": "4",
        "difficulty": "Easy 🌱",
        "explanation": "2 groups of 2 = 2 × 2 = 4 mangoes!"
    },
    {
        "question": "🌱 A farmer plants 3 rows. Each row has 2 plants. How many plants are there?",
        "choices": ["5", "6", "7", "8"],
        "answer": "6",
        "difficulty": "Easy 🌱",
        "explanation": "3 groups of 2 = 3 × 2 = 6 plants!"
    },
    {
        "question": "🥭 There are 4 mango trees. Each tree has 2 mangoes. How many mangoes?",
        "choices": ["6", "8", "10", "12"],
        "answer": "8",
        "difficulty": "Easy 🌱",
        "explanation": "4 × 2 = 8 mangoes!"
    },

    # MEDIUM
    {
        "question": "🌽 A farmer has 3 baskets. Each basket has 4 ears of corn. How many ears of corn?",
        "choices": ["7", "10", "12", "14"],
        "answer": "12",
        "difficulty": "Medium 🌿",
        "explanation": "3 groups of 4 = 3 × 4 = 12 ears of corn!"
    },
    {
        "question": "🥭 There are 5 mango trees. Each tree has 3 mangoes. How many mangoes?",
        "choices": ["10", "12", "15", "18"],
        "answer": "15",
        "difficulty": "Medium 🌿",
        "explanation": "5 × 3 = 15 mangoes!"
    },
    {
        "question": "🌱 A farmer plants 4 rows. Each row has 5 plants. How many plants?",
        "choices": ["15", "20", "25", "30"],
        "answer": "20",
        "difficulty": "Medium 🌿",
        "explanation": "4 × 5 = 20 plants!"
    },
    {
        "question": "🐔 There are 6 chickens. Each chicken has 2 chicks. How many chicks?",
        "choices": ["8", "10", "12", "14"],
        "answer": "12",
        "difficulty": "Medium 🌿",
        "explanation": "6 × 2 = 12 chicks!"
    },

    # DIFFICULT
    {
        "question": "🥭 A farmer picks 6 mangoes from each of 4 trees. How many mangoes?",
        "choices": ["20", "22", "24", "26"],
        "answer": "24",
        "difficulty": "Difficult 🌳",
        "explanation": "6 × 4 = 24 mangoes!"
    },
    {
        "question": "🌾 There are 5 rows of rice. Each row has 6 plants. How many rice plants?",
        "choices": ["25", "30", "35", "36"],
        "answer": "30",
        "difficulty": "Difficult 🌳",
        "explanation": "5 × 6 = 30 rice plants!"
    },
    {
        "question": "🥥 A farmer has 4 coconut trees. Each tree has 7 coconuts. How many coconuts?",
        "choices": ["21", "24", "28", "32"],
        "answer": "28",
        "difficulty": "Difficult 🌳",
        "explanation": "4 × 7 = 28 coconuts!"
    }
]


# ---------------------------------------------------------
# SESSION STATE
# ---------------------------------------------------------
if "questions" not in st.session_state:
    st.session_state.questions = random.sample(QUESTIONS, 10)

if "current_question" not in st.session_state:
    st.session_state.current_question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected_answer" not in st.session_state:
    st.session_state.selected_answer = None

if "game_finished" not in st.session_state:
    st.session_state.game_finished = False


# ---------------------------------------------------------
# TITLE
# ---------------------------------------------------------
st.markdown(
    '<div class="title">🥭🌱 Multiplication Farm Adventure 🌱🥭</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🚜 Help the farmer solve multiplication problems!</div>',
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# GAME FINISHED
# ---------------------------------------------------------
if st.session_state.game_finished:

    st.balloons()

    score = st.session_state.score

    st.markdown("## 🎉 Farm Adventure Complete! 🎉")

    st.markdown(
        f"""
        <div class="score-box">
            🏆 Your Score: {score} / 10
        </div>
        """,
        unsafe_allow_html=True
    )

    percentage = score * 10

    if percentage == 100:
        st.success("🌟 AMAZING! You are a Super Multiplication Farmer! 🥭🏆")
    elif percentage >= 80:
        st.success("🎉 Excellent work! Your farm is growing beautifully! 🌱")
    elif percentage >= 60:
        st.info("😊 Good job! Keep practicing multiplication!")
    else:
        st.warning("💪 Nice try! Let's practice some more multiplication!")

    st.markdown("### 🌾 You helped the farmer today!")

    if st.button("🔄 Play Again", use_container_width=True):
        st.session_state.questions = random.sample(QUESTIONS, 10)
        st.session_state.current_question = 0
        st.session_state.score = 0
        st.session_state.answered = False
        st.session_state.selected_answer = None
        st.session_state.game_finished = False
        st.rerun()

    st.stop()


# ---------------------------------------------------------
# CURRENT QUESTION
# ---------------------------------------------------------
question_number = st.session_state.current_question + 1
total_questions = len(st.session_state.questions)

current = st.session_state.questions[
    st.session_state.current_question
]

# ---------------------------------------------------------
# SCORE
# ---------------------------------------------------------
st.markdown(
    f"""
    <div class="score-box">
        🏆 Score: {st.session_state.score} / {total_questions}
    </div>
    """,
    unsafe_allow_html=True
)

st.write("")

# ---------------------------------------------------------
# PROGRESS
# ---------------------------------------------------------
st.write(f"🌱 Question {question_number} of {total_questions}")

progress = st.session_state.current_question / total_questions
st.progress(progress)

# ---------------------------------------------------------
# DIFFICULTY
# ---------------------------------------------------------
st.markdown(
    f"""
    <div style="text-align:center;">
        <span class="difficulty">
            {current["difficulty"]}
        </span>
    </div>
    """,
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# QUESTION
# ---------------------------------------------------------
st.markdown(
    f"""
    <div class="question-box">
        <div class="question">
            {current["question"]}
        </div>
    </div>
    """,
    unsafe_allow_html=True
)


# ---------------------------------------------------------
# ANSWER BUTTONS
# ---------------------------------------------------------
if not st.session_state.answered:

    st.write("### 👇 Choose your answer:")

    for i, choice in enumerate(current["choices"]):

        if st.button(
            f"🔵 {choice}",
            key=f"answer_{question_number}_{i}",
            use_container_width=True
        ):

            st.session_state.selected_answer = choice
            st.session_state.answered = True

            if choice == current["answer"]:
                st.session_state.score += 1

            st.rerun()


# ---------------------------------------------------------
# IMMEDIATE FEEDBACK
# ---------------------------------------------------------
else:

    selected = st.session_state.selected_answer

    if selected == current["answer"]:

        st.markdown(
            """
            <div class="feedback"
                 style="background-color:#DFF0D8;color:#2E7D32;">
                🎉 Correct! Great job! 🌟
            </div>
            """,
            unsafe_allow_html=True
        )

        st.write(f"💡 {current['explanation']}")

    else:

        st.markdown(
            """
            <div class="feedback"
                 style="background-color:#F8D7DA;color:#B71C1C;">
                😊 Not quite! Let's learn from it!
            </div>
            """,
            unsafe_allow_html=True
        )

        st.write(
            f"✅ The correct answer is **{current['answer']}**."
        )

        st.write(f"💡 {current['explanation']}")

    st.write("")

    # -----------------------------------------------------
    # NEXT QUESTION
    # -----------------------------------------------------
    if question_number < total_questions:

        if st.button(
            "➡️ Next Question",
            use_container_width=True
        ):
            st.session_state.current_question += 1
            st.session_state.answered = False
            st.session_state.selected_answer = None
            st.rerun()

    else:

        if st.button(
            "🏆 See My Result",
            use_container_width=True
        ):
            st.session_state.game_finished = True
            st.rerun()


# ---------------------------------------------------------
# FOOTER
# ---------------------------------------------------------
st.write("")
st.markdown(
    """
    <div style="text-align:center;color:#795548;">
        🚜 Keep learning • 🌱 Keep growing • 🥭 Keep multiplying!
    </div>
    """,
    unsafe_allow_html=True
)
```

### How to run it

Create a folder such as:

```text
multiplication-farm-game/
│
├── app.py
└── requirements.txt
```

Put this in `requirements.txt`:

```text
streamlit
```

### Run on your computer

Install Streamlit:

```bash
pip install streamlit
```

Then:

```bash
streamlit run app.py
```

The game will open in your browser.

### Deploy to Streamlit Community Cloud

1. Create a GitHub repository.
2. Upload:

   * `app.py`
   * `requirements.txt`
3. Go to **Streamlit Community Cloud**.
4. Select **Create app**.
5. Select your GitHub repository.
6. Choose `app.py` as the main file.
7. Click **Deploy**.

The game is designed to use only standard Python + Streamlit, so there are **no extra packages or APIs** required.

