# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwptv84Vq9KwDrkw0pcLy__dCb3yJtJq
"""

import streamlit as st
import random

# ---------------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Addition Adventure 🎈",
    page_icon="🧮",
    layout="centered"
)

# ---------------------------------------------------------
# CUSTOM CSS
# ---------------------------------------------------------
st.markdown("""
<style>
    .main {
        background-color: #FFF9E6;
    }

    .title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
    }

    .subtitle {
        text-align: center;
        font-size: 22px;
    }

    .question-box {
        background-color: #E8F5E9;
        padding: 25px;
        border-radius: 20px;
        text-align: center;
        font-size: 30px;
        margin: 20px 0;
    }

    .reward {
        background-color: #FFF3CD;
        padding: 20px;
        border-radius: 20px;
        text-align: center;
        font-size: 25px;
        border: 3px solid #FFD54F;
    }

    .feedback {
        background-color: #E3F2FD;
        padding: 20px;
        border-radius: 20px;
        font-size: 20px;
    }

    .level {
        text-align: center;
        font-size: 25px;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# QUESTIONS
# Concrete situations for children
# ---------------------------------------------------------

QUESTIONS = {
    1: [
        ("🍎 You have 2 apples. Your friend gives you 3 more. How many apples do you have?", 2, 3),
        ("🐔 There are 4 chickens. 2 more chickens come. How many chickens are there?", 4, 2),
        ("🥭 You pick 3 mangoes and then pick 2 more. How many mangoes?", 3, 2),
        ("🌸 You have 1 flower. You pick 4 more. How many flowers?", 1, 4),
        ("🐟 You catch 2 fish. Your brother catches 2 fish. How many fish?", 2, 2),
    ],

    2: [
        ("🥭 A basket has 5 mangoes. You add 3 more. How many mangoes?", 5, 3),
        ("🐄 There are 6 cows. 2 more cows arrive. How many cows?", 6, 2),
        ("🍌 You have 4 bananas and get 5 more. How many bananas?", 4, 5),
        ("🌱 You plant 7 seeds and then plant 2 more. How many seeds?", 7, 2),
        ("🐓 There are 5 chickens and 4 chicks. How many birds?", 5, 4),
    ],

    3: [
        ("🍎 A farmer has 8 apples and picks 5 more. How many apples?", 8, 5),
        ("🥭 You collect 7 mangoes and your friend gives you 6. How many?", 7, 6),
        ("🌽 There are 9 corn plants. You plant 4 more. How many plants?", 9, 4),
        ("🐐 A farmer has 6 goats and buys 7 more. How many goats?", 6, 7),
        ("🐟 You catch 8 fish and your father catches 5. How many fish?", 8, 5),
    ],

    4: [
        ("🍊 A basket has 12 oranges. You add 6 more. How many oranges?", 12, 6),
        ("🥭 A farmer picks 14 mangoes in the morning and 5 in the afternoon. How many?", 14, 5),
        ("🐔 There are 11 chickens and 8 chicks. How many birds?", 11, 8),
        ("🌱 You plant 13 seeds and your friend plants 7. How many seeds?", 13, 7),
        ("🍌 You have 15 bananas and receive 4 more. How many bananas?", 15, 4),
    ],

    5: [
        ("🥭 A farmer collects 18 mangoes and then collects 7 more. How many?", 18, 7),
        ("🌽 There are 16 corn plants. The farmer plants 9 more. How many?", 16, 9),
        ("🐄 A farmer has 17 cows and buys 8 more. How many cows?", 17, 8),
        ("🍎 A basket has 19 apples. You add 6 more apples. How many?", 19, 6),
        ("🐟 A fisherman catches 15 fish in the morning and 12 later. How many fish?", 15, 12),
    ]
}

# ---------------------------------------------------------
# SESSION STATE
# ---------------------------------------------------------

if "level" not in st.session_state:
    st.session_state.level = 1

if "question" not in st.session_state:
    st.session_state.question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "level_score" not in st.session_state:
    st.session_state.level_score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "reward" not in st.session_state:
    st.session_state.reward = ""

if "game_finished" not in st.session_state:
    st.session_state.game_finished = False

if "level_failed" not in st.session_state:
    st.session_state.level_failed = False


# ---------------------------------------------------------
# RESET GAME
# ---------------------------------------------------------

def reset_game():
    st.session_state.level = 1
    st.session_state.question = 0
    st.session_state.score = 0
    st.session_state.level_score = 0
    st.session_state.answered = False
    st.session_state.feedback = ""
    st.session_state.reward = ""
    st.session_state.game_finished = False
    st.session_state.level_failed = False


# ---------------------------------------------------------
# HEADER
# ---------------------------------------------------------

st.markdown(
    '<div class="title">🧮 Addition Adventure 🎈</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🌟 Learn Addition Through Fun! 🌟</div>',
    unsafe_allow_html=True
)

st.write("")

# ---------------------------------------------------------
# GAME FINISHED
# ---------------------------------------------------------

if st.session_state.game_finished:

    st.balloons()

    st.markdown(
        """
        <div class="reward">
        🏆🎉 AMAZING! 🎉🏆<br><br>
        You completed all 5 levels!<br>
        You are an <b>ADDITION SUPERSTAR!</b> ⭐
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    st.success(
        f"🎯 Your final score: {st.session_state.score} / 25"
    )

    st.markdown("### 🏅 Your Surprise Badges")

    st.write("🥉 Level 1 Explorer")
    st.write("🥈 Level 2 Addition Friend")
    st.write("🥇 Level 3 Math Hero")
    st.write("💎 Level 4 Math Champion")
    st.write("👑 Level 5 Addition Superstar")

    if st.button("🔄 PLAY AGAIN", use_container_width=True):
        reset_game()
        st.rerun()

    st.stop()


# ---------------------------------------------------------
# LEVEL FAILED
# ---------------------------------------------------------

if st.session_state.level_failed:

    st.error(
        f"🌱 You got {st.session_state.level_score}/5 correct."
    )

    st.markdown(
        """
        <div class="feedback">
        💡 Don't worry! Mistakes help our brains grow! 🧠🌱<br><br>
        You need <b>at least 3 correct answers</b> to move to the next level.
        </div>
        """,
        unsafe_allow_html=True
    )

    if st.button("🔁 TRY THIS LEVEL AGAIN", use_container_width=True):

        st.session_state.question = 0
        st.session_state.level_score = 0
        st.session_state.answered = False
        st.session_state.feedback = ""
        st.session_state.reward = ""
        st.session_state.level_failed = False

        st.rerun()

    st.stop()


# ---------------------------------------------------------
# LEVEL INFORMATION
# ---------------------------------------------------------

level = st.session_state.level
question_number = st.session_state.question

st.markdown(
    f'<div class="level">🌟 LEVEL {level} 🌟</div>',
    unsafe_allow_html=True
)

st.progress(
    question_number / 5,
    text=f"Question {question_number + 1} of 5"
)

# ---------------------------------------------------------
# SCORE
# ---------------------------------------------------------

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("⭐ Total Score", st.session_state.score)

with col2:
    st.metric("🎯 Level Score", st.session_state.level_score)

with col3:
    st.metric("🏆 Level", f"{level}/5")


# ---------------------------------------------------------
# CURRENT QUESTION
# ---------------------------------------------------------

question_text, num1, num2 = QUESTIONS[level][question_number]

st.markdown(
    f"""
    <div class="question-box">
    {question_text}
    <br><br>
    <b>{num1} + {num2} = ?</b>
    </div>
    """,
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# ANSWER
# ---------------------------------------------------------

if not st.session_state.answered:

    correct_answer = num1 + num2

    # Create answer choices
    choices = [
        correct_answer,
        correct_answer + 1,
        correct_answer - 1,
        correct_answer + 2
    ]

    # Remove negative values
    choices = [x for x in choices if x >= 0]

    # Remove duplicates
    choices = list(set(choices))

    # Make sure there are 4 choices
    while len(choices) < 4:
        new_choice = correct_answer + random.randint(-4, 5)
        if new_choice >= 0 and new_choice not in choices:
            choices.append(new_choice)

    random.shuffle(choices)

    st.markdown("### 👇 Choose your answer:")

    cols = st.columns(2)

    for i, answer in enumerate(choices):

        with cols[i % 2]:

            if st.button(
                f"🔢 {answer}",
                key=f"answer_{level}_{question_number}_{i}",
                use_container_width=True
            ):

                st.session_state.answered = True

                if answer == correct_answer:

                    st.session_state.level_score += 1
                    st.session_state.score += 1

                    rewards = [
                        "🎁 Surprise! You found a magic star! ⭐",
                        "🍭 Sweet reward! You earned a candy badge!",
                        "🌟 WOW! You earned a shining star!",
                        "🏅 Fantastic! You earned a Math Badge!",
                        "🎉 Amazing! You are a Math Hero!"
                    ]

                    st.session_state.reward = random.choice(rewards)

                    st.session_state.feedback = (
                        f"✅ Correct! {num1} + {num2} = {correct_answer}"
                    )

                else:

                    st.session_state.feedback = (
                        f"❌ Not quite! Let's try again mentally. "
                        f"{num1} + {num2} = {correct_answer}. "
                        f"Keep going! 💪🧠"
                    )

                st.rerun()


# ---------------------------------------------------------
# FEEDBACK
# ---------------------------------------------------------

else:

    if "✅" in st.session_state.feedback:

        st.success(st.session_state.feedback)

        st.markdown(
            f"""
            <div class="reward">
            {st.session_state.reward}
            </div>
            """,
            unsafe_allow_html=True
        )

        st.balloons()

    else:

        st.warning(st.session_state.feedback)

        st.markdown(
            """
            <div class="feedback">
            💡 Tip: Count the objects or use your fingers! 👆👆
            <br><br>
            Every mistake is a chance to learn. 🌱
            </div>
            """,
            unsafe_allow_html=True
        )

    # -----------------------------------------------------
    # NEXT QUESTION
    # -----------------------------------------------------

    if question_number < 4:

        if st.button(
            "➡️ NEXT QUESTION",
            use_container_width=True
        ):

            st.session_state.question += 1
            st.session_state.answered = False
            st.session_state.feedback = ""
            st.session_state.reward = ""

            st.rerun()

    else:

        # -------------------------------------------------
        # END OF LEVEL
        # -------------------------------------------------

        st.write("")

        if st.session_state.level_score >= 3:

            st.success(
                f"🎉 Level {level} complete! "
                f"You got {st.session_state.level_score}/5 correct!"
            )

            if level < 5:

                if st.button(
                    f"🚀 GO TO LEVEL {level + 1}",
                    use_container_width=True
                ):

                    st.session_state.level += 1
                    st.session_state.question = 0
                    st.session_state.level_score = 0
                    st.session_state.answered = False
                    st.session_state.feedback = ""
                    st.session_state.reward = ""

                    st.rerun()

            else:

                if st.button(
                    "🏆 FINISH GAME!",
                    use_container_width=True
                ):

                    st.session_state.game_finished = True
                    st.rerun()

        else:

            st.session_state.level_failed = True
            st.rerun()


# ---------------------------------------------------------
# GAME RULES
# ---------------------------------------------------------

with st.expander("📖 How to Play"):

    st.write("""
    🎮 **Game Rules**

    1. There are **5 levels**.
    2. Each level has **5 questions**.
    3. Choose the correct answer.
    4. ✅ Correct answer = surprise reward!
    5. ❌ Incorrect answer = helpful feedback.
    6. You need **at least 3 correct answers out of 5**.
    7. If you get 3 or more correct, you unlock the next level.
    8. Complete Level 5 to become an **Addition Superstar! 👑**
    """)

# ---------------------------------------------------------
# RESET BUTTON
# ---------------------------------------------------------

st.write("")

if st.button("🔄 Restart Game", use_container_width=True):
    reset_game()
    st.rerun()