# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDxZ9T6yfTkm7UxEQnX6LoG9k9KctGcp
"""

```python
import streamlit as st
import random

# =========================================================
# PAGE CONFIGURATION
# =========================================================
st.set_page_config(
    page_title="Konta no Tau Hamutuk! 🎮",
    page_icon="➕",
    layout="centered"
)

# =========================================================
# CUSTOM CSS
# =========================================================
st.markdown("""
<style>
    .main-title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        color: #FF6B35;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 22px;
        color: #444444;
        margin-bottom: 20px;
    }

    .object-box {
        background-color: #FFF8E7;
        border-radius: 20px;
        padding: 25px;
        text-align: center;
        border: 3px solid #FFD166;
        margin: 15px 0;
    }

    .objects {
        font-size: 45px;
        letter-spacing: 8px;
    }

    .equation {
        font-size: 38px;
        font-weight: bold;
        color: #118AB2;
        text-align: center;
        margin: 15px;
    }

    .success-box {
        background-color: #D8F3DC;
        border-radius: 15px;
        padding: 20px;
        text-align: center;
        border: 3px solid #52B788;
        font-size: 22px;
    }

    .wrong-box {
        background-color: #FFE5E5;
        border-radius: 15px;
        padding: 20px;
        text-align: center;
        border: 3px solid #FF6B6B;
        font-size: 20px;
    }

    .badge {
        text-align: center;
        font-size: 50px;
        padding: 15px;
    }

    .level-box {
        background-color: #E8F4FD;
        border-radius: 15px;
        padding: 15px;
        text-align: center;
        margin-bottom: 15px;
    }

    .stButton > button {
        width: 100%;
        border-radius: 15px;
        font-size: 20px;
        font-weight: bold;
        padding: 10px;
    }
</style>
""", unsafe_allow_html=True)

# =========================================================
# GAME DATA
# =========================================================

objects = [
    ("🍎", "ai-fuan"),
    ("🥭", "manga"),
    ("🌽", "milho"),
    ("🍌", "hudi"),
    ("🥥", "nuu"),
    ("🍊", "laranja"),
    ("🐔", "manu"),
    ("🥚", "tolun"),
    ("🌱", "ai-oan"),
]

# Maximum addition number for each level
level_limits = {
    1: 5,
    2: 10,
    3: 15,
    4: 20,
    5: 30
}

# =========================================================
# SESSION STATE
# =========================================================

if "level" not in st.session_state:
    st.session_state.level = 1

if "question" not in st.session_state:
    st.session_state.question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "correct" not in st.session_state:
    st.session_state.correct = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "badge" not in st.session_state:
    st.session_state.badge = ""

if "current_problem" not in st.session_state:
    st.session_state.current_problem = None

if "game_started" not in st.session_state:
    st.session_state.game_started = False


# =========================================================
# CREATE NEW QUESTION
# =========================================================

def create_question(level):

    maximum = level_limits[level]

    # Keep numbers appropriate for young children
    if level == 1:
        a = random.randint(1, 3)
        b = random.randint(1, 3)

    elif level == 2:
        a = random.randint(1, 5)
        b = random.randint(1, 5)

    elif level == 3:
        a = random.randint(2, 8)
        b = random.randint(1, 7)

    elif level == 4:
        a = random.randint(3, 10)
        b = random.randint(2, 10)

    else:
        a = random.randint(5, 15)
        b = random.randint(3, 15)

    emoji, object_name = random.choice(objects)

    return {
        "a": a,
        "b": b,
        "answer": a + b,
        "emoji": emoji,
        "name": object_name
    }


# =========================================================
# START GAME
# =========================================================

if not st.session_state.game_started:

    st.markdown(
        '<div class="main-title">🎮 Konta no Tau Hamutuk!</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">➕ Jogu Soma ba Labarik 6–7 Tinan</div>',
        unsafe_allow_html=True
    )

    st.markdown("""
    ### 👋 Bem-vindu!

    Iha jogu ida-ne'e ita sei aprende **soma númeru** ho objetu sira
    ne'ebé ita bele haree iha moris loroloron.

    🍎 Ai-fuan
    🥭 Manga
    🌽 Milho
    🐔 Manu
    🥚 Tolun
    🌱 Ai-oan

    **Regra:**
    - 🎯 Level ida iha pergunta 5.
    - ⭐ Ita presiza hetan pelo menus **3 resposta loos** atu pasa ba level tuir mai.
    - 🎉 Resposta loos hetan surpresa no badge!
    - 💡 Resposta sala sei fó ajuda atu ita bele aprende.
    """)

    st.markdown("---")

    if st.button("🚀 Hahu Jogu!", type="primary"):
        st.session_state.game_started = True
        st.session_state.current_problem = create_question(
            st.session_state.level
        )
        st.rerun()

    st.stop()


# =========================================================
# HEADER
# =========================================================

st.markdown(
    '<div class="main-title">🎮 Konta no Tau Hamutuk!</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">➕ Aprende Soma ho Objetu Reál</div>',
    unsafe_allow_html=True
)

# =========================================================
# STATUS
# =========================================================

level = st.session_state.level
question_number = st.session_state.question + 1

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("🏆 Level", f"{level}/5")

with col2:
    st.metric("⭐ Pontu", st.session_state.score)

with col3:
    st.metric("✅ Los", st.session_state.correct)

progress = st.session_state.question / 5
st.progress(progress)

st.markdown(
    f"""
    <div class="level-box">
        <h2>🌟 Level {level}</h2>
        <p>Pergunta {question_number} husi 5</p>
    </div>
    """,
    unsafe_allow_html=True
)

# =========================================================
# CURRENT QUESTION
# =========================================================

if st.session_state.current_problem is None:
    st.session_state.current_problem = create_question(level)

problem = st.session_state.current_problem

a = problem["a"]
b = problem["b"]
answer = problem["answer"]
emoji = problem["emoji"]

# =========================================================
# SHOW REAL OBJECTS
# =========================================================

st.markdown(
    '<div class="object-box">',
    unsafe_allow_html=True
)

st.markdown("### 👀 Haree objetu sira!")

st.markdown(
    f'<div class="objects">{" ".join([emoji] * a)}</div>',
    unsafe_allow_html=True
)

st.markdown(f"<h3>{a} objetu</h3>", unsafe_allow_html=True)

st.markdown("<h2>➕</h2>", unsafe_allow_html=True)

st.markdown(
    f'<div class="objects">{" ".join([emoji] * b)}</div>',
    unsafe_allow_html=True
)

st.markdown(f"<h3>{b} objetu</h3>", unsafe_allow_html=True)

st.markdown(
    f'<div class="equation">{a} + {b} = ?</div>',
    unsafe_allow_html=True
)

st.markdown("</div>", unsafe_allow_html=True)


# =========================================================
# ANSWER SECTION
# =========================================================

if not st.session_state.answered:

    st.markdown("### 🤔 Resposta saida loos?")

    # Create 4 answer choices
    choices = {answer}

    while len(choices) < 4:
        wrong = answer + random.randint(-4, 5)

        if wrong >= 0:
            choices.add(wrong)

    choices = list(choices)
    random.shuffle(choices)

    cols = st.columns(2)

    for i, choice in enumerate(choices):

        with cols[i % 2]:

            if st.button(
                f"🔢 {choice}",
                key=f"answer_{question_number}_{i}"
            ):

                st.session_state.answered = True

                if choice == answer:

                    st.session_state.correct += 1
                    st.session_state.score += 10

                    surprises = [
                        "🎉 SURPRESA! Ita halo diak!",
                        "🌟 Diak loos! Ita hatene soma!",
                        "👏 Parabéns! Resposta loos!",
                        "🎊 Uau! Ita matenek tebes!",
                        "🏅 Excelente! Kontinua hanesan ne'e!"
                    ]

                    badges = [
                        "⭐ Estrela Soma",
                        "🏆 Campeaun Soma",
                        "🥇 Matemátiku Ki'ik",
                        "🌟 Super Konta",
                        "🎖️ Mestre Soma"
                    ]

                    st.session_state.feedback = random.choice(surprises)
                    st.session_state.badge = random.choice(badges)

                else:

                    st.session_state.feedback = (
                        f"💡 Quase! La bele preocupa. "
                        f"Haree fali objetu sira no konta hamutuk. "
                        f"Resposta loos mak **{answer}**."
                    )

                st.rerun()


# =========================================================
# FEEDBACK
# =========================================================

if st.session_state.answered:

    if st.session_state.badge:

        st.markdown(
            f"""
            <div class="success-box">
                <div class="badge">🎁 {st.session_state.badge}</div>
                <h2>{st.session_state.feedback}</h2>
                <p>⭐ +10 pontu!</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        st.balloons()

    else:

        st.markdown(
            f"""
            <div class="wrong-box">
                <h3>{st.session_state.feedback}</h3>
                <p>💪 Koko! Ita bele aprende hosi erru.</p>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("")

    # =====================================================
    # NEXT QUESTION
    # =====================================================

    if st.session_state.question < 4:

        if st.button("➡️ Pergunta Tuir Mai", type="primary"):

            st.session_state.question += 1
            st.session_state.answered = False
            st.session_state.feedback = ""
            st.session_state.badge = ""
            st.session_state.current_problem = create_question(
                st.session_state.level
            )

            st.rerun()

    else:

        # =================================================
        # LEVEL COMPLETE
        # =================================================

        st.markdown("---")

        st.markdown("## 🎯 Level Remata!")

        correct = st.session_state.correct

        if correct >= 3:

            if level < 5:

                st.success(
                    f"🎉 Parabéns! Ita hetan {correct}/5 resposta loos! "
                    f"Ita bele tama ba Level {level + 1}."
                )

                if st.button(
                    f"🚀 Tama ba Level {level + 1}",
                    type="primary"
                ):

                    st.session_state.level += 1
                    st.session_state.question = 0
                    st.session_state.correct = 0
                    st.session_state.answered = False
                    st.session_state.feedback = ""
                    st.session_state.badge = ""
                    st.session_state.current_problem = create_question(
                        st.session_state.level
                    )

                    st.rerun()

            else:

                st.balloons()

                st.success(
                    "🏆 PARABÉNS! Ita remata Level 5!"
                )

                st.markdown(
                    """
                    <div class="success-box">
                        <h1>👑 MESTRE SOMA! 👑</h1>
                        <p>
                        Ita hatene ona soma ho númeru no objetu reál.
                        </p>
                        <div class="badge">🏆 🌟 🎉 🥇 🎊</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

        else:

            st.warning(
                f"💪 Ita hetan {correct}/5 resposta loos. "
                "Ita presiza pelo menus 3 atu pasa level."
            )

            if st.button(
                "🔄 Repete Level",
                type="primary"
            ):

                st.session_state.question = 0
                st.session_state.correct = 0
                st.session_state.answered = False
                st.session_state.feedback = ""
                st.session_state.badge = ""
                st.session_state.current_problem = create_question(
                    st.session_state.level
                )

                st.rerun()


# =========================================================
# RESTART GAME
# =========================================================

st.markdown("---")

if st.button("🔄 Hahu Fali husi Level 1"):

    st.session_state.level = 1
    st.session_state.question = 0
    st.session_state.score = 0
    st.session_state.correct = 0
    st.session_state.answered = False
    st.session_state.feedback = ""
    st.session_state.badge = ""
    st.session_state.current_problem = create_question(1)

    st.rerun()

# =========================================================
# FOOTER
# =========================================================

st.markdown(
    """
    <div style="text-align:center; padding:20px;">
        <p>🌱 Aprende • 🎮 Joga • 🧠 Konta • 🌟 Sai matenek!</p>
        <p><b>Matemátika bele sai divertida!</b> 😊</p>
    </div>
    """,
    unsafe_allow_html=True
)
```