# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAWJmXw0KM1f45BeeHrdziu505lpN0LD
"""

import streamlit as st
import random

# ============================================================
# CONFIGURAÇÃO DA PÁGINA
# ============================================================

st.set_page_config(
    page_title="Aventura da Adição",
    page_icon="➕",
    layout="centered"
)

# ============================================================
# CSS - INTERFACE COLORIDA PARA CRIANÇAS
# ============================================================

st.markdown("""
<style>

.main {
    background-color: #FFF8E7;
}

.title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
    color: #FF6B35;
}

.subtitle {
    text-align: center;
    font-size: 22px;
    color: #555;
}

.question-box {
    background-color: #FFFFFF;
    padding: 25px;
    border-radius: 20px;
    text-align: center;
    box-shadow: 0px 4px 12px rgba(0,0,0,0.12);
    margin: 20px 0;
}

.objects {
    font-size: 48px;
    text-align: center;
    letter-spacing: 8px;
}

.feedback-correct {
    background-color: #D4EDDA;
    padding: 18px;
    border-radius: 15px;
    color: #155724;
    font-size: 22px;
    text-align: center;
    font-weight: bold;
}

.feedback-wrong {
    background-color: #F8D7DA;
    padding: 18px;
    border-radius: 15px;
    color: #721C24;
    font-size: 20px;
    text-align: center;
}

.badge {
    background-color: #FFE066;
    padding: 20px;
    border-radius: 20px;
    text-align: center;
    font-size: 25px;
    font-weight: bold;
}

</style>
""", unsafe_allow_html=True)

# ============================================================
# DADOS DOS NÍVEIS
# ============================================================

LEVELS = {
    1: {
        "nome": "Nível 1 – Pequenos Exploradores 🌱",
        "max": 5,
        "objetos": ["🍎", "🍌", "🥭"],
        "min": 1
    },
    2: {
        "nome": "Nível 2 – Jovens Matemáticos ⭐",
        "max": 10,
        "objetos": ["🍊", "🥭", "🍎", "🥕"],
        "min": 2
    },
    3: {
        "nome": "Nível 3 – Grandes Descobridores 🚀",
        "max": 15,
        "objetos": ["🥭", "🍌", "🍊", "🌽"],
        "min": 3
    },
    4: {
        "nome": "Nível 4 – Mestres da Adição 🧠",
        "max": 20,
        "objetos": ["🍎", "🥭", "🌽", "🥕"],
        "min": 4
    },
    5: {
        "nome": "Nível 5 – Campeões da Matemática 🏆",
        "max": 25,
        "objetos": ["🥭", "🍎", "🍊", "🌽"],
        "min": 5
    }
}

BADGES = [
    "🌟 Estrela da Matemática!",
    "🏅 Campeão da Adição!",
    "🎖️ Mestre dos Números!",
    "👑 Rei/Rainha da Matemática!",
    "🚀 Super Matemático!"
]

# ============================================================
# INICIALIZAÇÃO DO JOGO
# ============================================================

def iniciar_jogo():
    st.session_state.level = 1
    st.session_state.question = 1
    st.session_state.score = 0
    st.session_state.correct_level = 0
    st.session_state.total_answered = 0
    st.session_state.game_over = False
    st.session_state.finished_level = False
    st.session_state.feedback = None
    st.session_state.question_data = gerar_pergunta(1)


def gerar_pergunta(level):
    dados = LEVELS[level]

    a = random.randint(dados["min"], dados["max"])
    b = random.randint(dados["min"], dados["max"])

    objeto = random.choice(dados["objetos"])

    return {
        "a": a,
        "b": b,
        "answer": a + b,
        "object": objeto
    }


# ============================================================
# CRIAR AS OPÇÕES DE RESPOSTA
# ============================================================

def criar_opcoes(resposta):
    opcoes = {resposta}

    while len(opcoes) < 4:
        variacao = random.randint(-4, 4)
        nova = resposta + variacao

        if nova >= 0:
            opcoes.add(nova)

    opcoes = list(opcoes)
    random.shuffle(opcoes)

    return opcoes


# ============================================================
# FEEDBACK
# ============================================================

def mostrar_feedback(correct, answer, user_answer):

    if correct:

        st.markdown(
            f"""
            <div class="feedback-correct">
            🎉 MUITO BEM! 🎉<br><br>
            A resposta é <b>{answer}</b>!<br>
            ⭐ Excelente trabalho!
            </div>
            """,
            unsafe_allow_html=True
        )

        st.balloons()

        st.markdown(
            f"""
            <div class="badge">
            🎁 SURPRESA! 🎁<br><br>
            🏆 Você ganhou uma estrela!<br>
            {random.choice(BADGES)}
            </div>
            """,
            unsafe_allow_html=True
        )

    else:

        st.markdown(
            f"""
            <div class="feedback-wrong">
            💡 Quase lá!<br><br>
            Você respondeu <b>{user_answer}</b>.<br>
            A resposta correta é <b>{answer}</b>.<br><br>
            🌱 Não desista! Tente novamente na próxima pergunta!
            </div>
            """,
            unsafe_allow_html=True
        )


# ============================================================
# INÍCIO DO PROGRAMA
# ============================================================

if "level" not in st.session_state:
    iniciar_jogo()


# ============================================================
# TÍTULO
# ============================================================

st.markdown(
    '<div class="title">➕ AVENTURA DA ADIÇÃO 🌈</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Aprende Matemática Brincando! 🎮</div>',
    unsafe_allow_html=True
)

st.write("")


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("🎮 Meu Jogo")

    st.write(f"🏆 **Pontuação:** {st.session_state.score}")

    st.write(
        f"⭐ **Nível:** {st.session_state.level}/5"
    )

    st.write(
        f"✅ **Respostas corretas:** "
        f"{st.session_state.correct_level}/5"
    )

    st.write(
        f"❓ **Pergunta:** "
        f"{st.session_state.question}/5"
    )

    st.write("")

    st.info(
        "💡 Para passar de nível, "
        "você precisa acertar pelo menos "
        "**3 das 5 perguntas**."
    )

    if st.button("🔄 Começar Novamente", use_container_width=True):
        iniciar_jogo()
        st.rerun()


# ============================================================
# JOGO TERMINADO
# ============================================================

if st.session_state.game_over:

    st.success("🎉 PARABÉNS! VOCÊ TERMINOU O JOGO! 🎉")

    st.markdown(
        f"""
        <div class="badge">
        🏆 CAMPEÃO DA ADIÇÃO 🏆<br><br>
        Pontuação final: {st.session_state.score} pontos ⭐
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    st.write(
        "🌟 Você completou os 5 níveis da Aventura da Adição!"
    )

    st.write(
        "🎁 Você é um verdadeiro Super Matemático!"
    )

    if st.button("🔄 Jogar Novamente", use_container_width=True):
        iniciar_jogo()
        st.rerun()

    st.stop()


# ============================================================
# INFORMAÇÕES DO NÍVEL
# ============================================================

level = st.session_state.level
dados = LEVELS[level]

st.subheader(dados["nome"])

progress = (st.session_state.question - 1) / 5

st.progress(progress)

st.write(
    f"Pergunta {st.session_state.question} de 5"
)

st.write(
    f"⭐ Respostas corretas neste nível: "
    f"{st.session_state.correct_level}/5"
)


# ============================================================
# PERGUNTA
# ============================================================

q = st.session_state.question_data

a = q["a"]
b = q["b"]
answer = q["answer"]
objeto = q["object"]


st.markdown(
    '<div class="question-box">',
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <div class="objects">
    {objeto * a}
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <h2>+
    </h2>
    """,
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <div class="objects">
    {objeto * b}
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <h1>{a} + {b} = ?</h1>
    """,
    unsafe_allow_html=True
)

st.markdown(
    '</div>',
    unsafe_allow_html=True
)


# ============================================================
# OPÇÕES
# ============================================================

if "options" not in st.session_state:
    st.session_state.options = criar_opcoes(answer)

options = st.session_state.options


# ============================================================
# RESPOSTA
# ============================================================

if st.session_state.feedback is None:

    st.write("### 👇 Escolha a resposta correta:")

    col1, col2 = st.columns(2)

    with col1:

        if st.button(
            f"🔵 {options[0]}",
            use_container_width=True
        ):

            user_answer = options[0]

            if user_answer == answer:

                st.session_state.score += 10
                st.session_state.correct_level += 1

                st.session_state.feedback = "correct"

            else:

                st.session_state.feedback = "wrong"

            st.session_state.total_answered += 1

            st.rerun()

        if st.button(
            f"🟢 {options[1]}",
            use_container_width=True
        ):

            user_answer = options[1]

            if user_answer == answer:

                st.session_state.score += 10
                st.session_state.correct_level += 1

                st.session_state.feedback = "correct"

            else:

                st.session_state.feedback = "wrong"

            st.session_state.total_answered += 1

            st.rerun()

    with col2:

        if st.button(
            f"🟡 {options[2]}",
            use_container_width=True
        ):

            user_answer = options[2]

            if user_answer == answer:

                st.session_state.score += 10
                st.session_state.correct_level += 1

                st.session_state.feedback = "correct"

            else:

                st.session_state.feedback = "wrong"

            st.session_state.total_answered += 1

            st.rerun()

        if st.button(
            f"🔴 {options[3]}",
            use_container_width=True
        ):

            user_answer = options[3]

            if user_answer == answer:

                st.session_state.score += 10
                st.session_state.correct_level += 1

                st.session_state.feedback = "correct"

            else:

                st.session_state.feedback = "wrong"

            st.session_state.total_answered += 1

            st.rerun()


# ============================================================
# MOSTRAR FEEDBACK
# ============================================================

else:

    correct = st.session_state.feedback == "correct"

    # Para feedback da resposta errada,
    # calculamos uma resposta representativa
    if correct:
        user_answer = answer
    else:
        user_answer = "incorreta"

    if correct:

        st.markdown(
            f"""
            <div class="feedback-correct">
            🎉 MUITO BEM! 🎉<br><br>
            {a} + {b} = <b>{answer}</b><br><br>
            ⭐ Você ganhou 10 pontos!
            </div>
            """,
            unsafe_allow_html=True
        )

        st.balloons()

        st.markdown(
            f"""
            <div class="badge">
            🎁 SURPRESA! 🎁<br><br>
            🏆 Você ganhou uma medalha!<br>
            {random.choice(BADGES)}
            </div>
            """,
            unsafe_allow_html=True
        )

    else:

        st.markdown(
            f"""
            <div class="feedback-wrong">
            💡 QUASE!<br><br>
            Vamos contar juntos! 🧮<br><br>
            {a} + {b} = <b>{answer}</b><br><br>
            🌱 Não desista! Você consegue!
            </div>
            """,
            unsafe_allow_html=True
        )

    st.write("")

    # ========================================================
    # VERIFICAR SE TERMINOU O NÍVEL
    # ========================================================

    if st.session_state.question >= 5:

        st.write("")

        if st.session_state.correct_level >= 3:

            st.success(
                f"🎉 Parabéns! Você acertou "
                f"{st.session_state.correct_level} de 5!"
            )

            if level < 5:

                st.markdown(
                    f"""
                    <div class="badge">
                    🔓 NOVO NÍVEL DESBLOQUEADO! 🔓<br><br>
                    Você pode avançar para o Nível {level + 1}! 🚀
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                if st.button(
                    "🚀 Ir para o Próximo Nível",
                    use_container_width=True
                ):

                    st.session_state.level += 1
                    st.session_state.question = 1
                    st.session_state.correct_level = 0
                    st.session_state.feedback = None
                    st.session_state.question_data = gerar_pergunta(
                        st.session_state.level
                    )
                    st.session_state.options = criar_opcoes(
                        st.session_state.question_data["answer"]
                    )

                    st.rerun()

            else:

                st.session_state.game_over = True

                st.write(
                    "🏆 Você completou todos os níveis!"
                )

                if st.button(
                    "🏆 Ver Resultado Final",
                    use_container_width=True
                ):
                    st.rerun()

        else:

            st.warning(
                f"🌱 Você acertou apenas "
                f"{st.session_state.correct_level} de 5."
            )

            st.write(
                "Para avançar, precisa acertar pelo menos "
                "**3 perguntas**."
            )

            if st.button(
                "🔁 Tentar o Nível Novamente",
                use_container_width=True
            ):

                st.session_state.question = 1
                st.session_state.correct_level = 0
                st.session_state.feedback = None
                st.session_state.question_data = gerar_pergunta(
                    level
                )

                st.session_state.options = criar_opcoes(
                    st.session_state.question_data["answer"]
                )

                st.rerun()

    else:

        if st.button(
            "➡️ Próxima Pergunta",
            use_container_width=True
        ):

            st.session_state.question += 1
            st.session_state.feedback = None

            st.session_state.question_data = gerar_pergunta(
                level
            )

            st.session_state.options = criar_opcoes(
                st.session_state.question_data["answer"]
            )

            st.rerun()


# ============================================================
# RODAPÉ
# ============================================================

st.write("")

st.markdown(
    """
    <div style="text-align:center;">
    🌈 Aprende • 🧮 Conta • ⭐ Ganha • 🏆 Diverte-te!
    </div>
    """,
    unsafe_allow_html=True
)