# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2IobuzFROesxmWlSj1oaNN9-gp7qOCQ
"""

import streamlit as st
import random
import time

# ============================================================
# PAGE CONFIGURATION
# ============================================================
st.set_page_config(
    page_title="Equation Challenge 🚀",
    page_icon="🧮",
    layout="centered"
)

# ============================================================
# CUSTOM CSS
# ============================================================
st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #eef2ff, #f8fafc);
    }

    .game-title {
        text-align: center;
        font-size: 45px;
        font-weight: bold;
        margin-bottom: 0px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #555;
        margin-bottom: 25px;
    }

    .score-box {
        padding: 15px;
        border-radius: 15px;
        background-color: white;
        text-align: center;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.08);
    }

    .equation-box {
        padding: 30px;
        border-radius: 20px;
        background-color: white;
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        margin: 25px 0px;
        box-shadow: 0px 5px 20px rgba(0,0,0,0.12);
    }

    .success {
        padding: 20px;
        border-radius: 15px;
        background-color: #dcfce7;
        color: #166534;
        font-size: 20px;
        text-align: center;
    }

    .wrong {
        padding: 20px;
        border-radius: 15px;
        background-color: #fee2e2;
        color: #991b1b;
        font-size: 20px;
        text-align: center;
    }

    .info-box {
        padding: 15px;
        border-radius: 12px;
        background-color: #e0f2fe;
        color: #075985;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================
# SESSION STATE
# ============================================================
if "score" not in st.session_state:
    st.session_state.score = 0

if "lives" not in st.session_state:
    st.session_state.lives = 3

if "question" not in st.session_state:
    st.session_state.question = None

if "answer" not in st.session_state:
    st.session_state.answer = None

if "hint" not in st.session_state:
    st.session_state.hint = ""

if "question_number" not in st.session_state:
    st.session_state.question_number = 1

if "answered" not in st.session_state:
    st.session_state.answered = False

if "message" not in st.session_state:
    st.session_state.message = ""

if "difficulty" not in st.session_state:
    st.session_state.difficulty = "Easy"


# ============================================================
# QUESTION GENERATORS
# ============================================================

def generate_easy():
    """
    One-step equations:
    x + a = b
    x - a = b
    ax = b
    x/a = b
    """

    x = random.randint(1, 20)
    operation = random.choice(["+", "-", "*", "/"])

    if operation == "+":
        a = random.randint(1, 20)
        result = x + a
        question = f"x + {a} = {result}"
        hint = f"Subtract {a} from both sides."

    elif operation == "-":
        a = random.randint(1, 15)
        result = x - a

        if result < 0:
            x = x + a
            result = x - a

        question = f"x - {a} = {result}"
        hint = f"Add {a} to both sides."

    elif operation == "*":
        a = random.randint(2, 10)
        result = x * a
        question = f"{a}x = {result}"
        hint = f"Divide both sides by {a}."

    else:
        a = random.randint(2, 10)
        x = x * a
        result = x // a
        question = f"x ÷ {a} = {result}"
        hint = f"Multiply both sides by {a}."

    return question, x, hint


def generate_medium():
    """
    Two-step equations:
    ax + b = c
    ax - b = c
    """

    x = random.randint(1, 15)
    a = random.randint(2, 8)
    b = random.randint(1, 15)

    operation = random.choice(["+", "-"])

    if operation == "+":
        result = a * x + b
        question = f"{a}x + {b} = {result}"
        hint = f"First subtract {b}, then divide by {a}."

    else:
        result = a * x - b

        if result < 0:
            x = random.randint(3, 15)
            result = a * x - b

        question = f"{a}x - {b} = {result}"
        hint = f"First add {b}, then divide by {a}."

    return question, x, hint


def generate_hard():
    """
    Equations with variables on both sides:
    ax + b = cx + d
    """

    x = random.randint(1, 12)

    a = random.randint(2, 8)
    c = random.randint(1, a - 1)

    b = random.randint(1, 15)
    d = a * x + b - c * x

    question = f"{a}x + {b} = {c}x + {d}"

    hint = (
        f"Move {c}x to the left side, "
        f"then move {b} to the right side."
    )

    return question, x, hint


# ============================================================
# NEW QUESTION
# ============================================================

def new_question():
    difficulty = st.session_state.difficulty

    if difficulty == "Easy":
        q, ans, hint = generate_easy()

    elif difficulty == "Medium":
        q, ans, hint = generate_medium()

    else:
        q, ans, hint = generate_hard()

    st.session_state.question = q
    st.session_state.answer = ans
    st.session_state.hint = hint
    st.session_state.answered = False
    st.session_state.message = ""


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="game-title">🧮 Equation Challenge 🚀</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Grade 7 Mathematics Adventure</div>',
    unsafe_allow_html=True
)

# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("🎮 Game Settings")

    difficulty = st.selectbox(
        "Choose Level",
        ["Easy", "Medium", "Hard"]
    )

    if difficulty != st.session_state.difficulty:
        st.session_state.difficulty = difficulty
        new_question()

    st.divider()

    st.subheader("📚 Learning Goal")

    if difficulty == "Easy":
        st.write("Solve one-step equations.")

    elif difficulty == "Medium":
        st.write("Solve two-step equations.")

    else:
        st.write("Solve equations with variables on both sides.")

    st.divider()

    st.subheader("🏆 Scoring")

    st.write("🟢 Easy → +10 points")
    st.write("🟡 Medium → +20 points")
    st.write("🔴 Hard → +30 points")

    st.divider()

    if st.button("🔄 Restart Game", use_container_width=True):
        st.session_state.score = 0
        st.session_state.lives = 3
        st.session_state.question_number = 1
        new_question()
        st.rerun()


# ============================================================
# INITIAL QUESTION
# ============================================================

if st.session_state.question is None:
    new_question()


# ============================================================
# SCORE BOARD
# ============================================================

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown(
        f"""
        <div class="score-box">
        ⭐<br>
        <b>Score</b><br>
        {st.session_state.score}
        </div>
        """,
        unsafe_allow_html=True
    )

with col2:
    st.markdown(
        f"""
        <div class="score-box">
        ❤️<br>
        <b>Lives</b><br>
        {st.session_state.lives}
        </div>
        """,
        unsafe_allow_html=True
    )

with col3:
    st.markdown(
        f"""
        <div class="score-box">
        📝<br>
        <b>Question</b><br>
        {st.session_state.question_number}
        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# PROGRESS
# ============================================================

progress = min(
    (st.session_state.question_number - 1) / 10,
    1.0
)

st.progress(progress)

# ============================================================
# EQUATION
# ============================================================

st.markdown(
    f"""
    <div class="equation-box">
        {st.session_state.question}
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    "<h3 style='text-align:center;'>What is the value of x?</h3>",
    unsafe_allow_html=True
)


# ============================================================
# ANSWER INPUT
# ============================================================

answer = st.number_input(
    "Enter your answer:",
    step=1,
    value=0
)


# ============================================================
# BUTTONS
# ============================================================

col1, col2 = st.columns(2)

with col1:

    check = st.button(
        "✅ CHECK ANSWER",
        use_container_width=True
    )

with col2:

    hint_button = st.button(
        "💡 HINT",
        use_container_width=True
    )


# ============================================================
# HINT
# ============================================================

if hint_button:

    st.info(
        f"💡 Hint: {st.session_state.hint}"
    )


# ============================================================
# CHECK ANSWER
# ============================================================

if check and not st.session_state.answered:

    st.session_state.answered = True

    if answer == st.session_state.answer:

        if difficulty == "Easy":
            points = 10
        elif difficulty == "Medium":
            points = 20
        else:
            points = 30

        st.session_state.score += points

        st.session_state.message = "correct"

        st.balloons()

    else:

        st.session_state.lives -= 1
        st.session_state.message = "wrong"


# ============================================================
# FEEDBACK
# ============================================================

if st.session_state.message == "correct":

    st.markdown(
        f"""
        <div class="success">
        🎉 <b>Excellent!</b><br>
        Your answer is correct!<br>
        +{10 if difficulty == "Easy" else 20 if difficulty == "Medium" else 30} points ⭐
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    if st.button("➡️ NEXT QUESTION", use_container_width=True):

        st.session_state.question_number += 1
        new_question()
        st.rerun()


elif st.session_state.message == "wrong":

    st.markdown(
        f"""
        <div class="wrong">
        ❌ <b>Not quite!</b><br>
        Try another question.
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write(
        f"Correct answer: **x = {st.session_state.answer}**"
    )

    if st.session_state.lives > 0:

        if st.button("➡️ TRY NEXT QUESTION", use_container_width=True):

            st.session_state.question_number += 1
            new_question()
            st.rerun()

    else:

        st.error("💥 Game Over!")

        st.markdown(
            f"""
            <h2 style='text-align:center;'>
            🏆 Final Score: {st.session_state.score}
            </h2>
            """,
            unsafe_allow_html=True
        )

        if st.button("🔄 PLAY AGAIN", use_container_width=True):

            st.session_state.score = 0
            st.session_state.lives = 3
            st.session_state.question_number = 1
            new_question()
            st.rerun()


# ============================================================
# TEACHING TIP
# ============================================================

st.divider()

st.markdown(
    """
    <div class="info-box">
    <b>👨‍🏫 Teacher Tip</b><br>
    Ask students to explain the operation they used to isolate
    <b>x</b>. Encourage them to use mathematical language such as
    <i>inverse operation</i>, <i>balance</i>, and
    <i>both sides of the equation</i>.
    </div>
    """,
    unsafe_allow_html=True
)