# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ux2SpCCEqfNIp3tWxo_gISlBhzVDZhHN
"""

Absolutely! Below is a **complete Grade 7 Equation Game** built with **Python + Streamlit**. It is designed to be colorful, interactive, and easy to deploy.

### 🎮 Features

* 🧮 Linear equations for Grade 7
* 🟢 Easy, 🟡 Medium, 🔴 Difficult levels
* ❓ 10 multiple-choice questions
* 4 answer choices
* ⭐ Score system
* 📊 Progress bar
* 💡 Instant feedback and explanations
* 🏆 Final score and performance message
* 🔄 Play Again button
* 🌾 Real-life contexts such as farming, fruits, school supplies
* 🎨 Attractive interface

### 1. Create `app.py`

```python
import streamlit as st
import random

# ---------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------
st.set_page_config(
    page_title="Equation Quest 🎮",
    page_icon="🧮",
    layout="centered"
)

# ---------------------------------------------------
# CUSTOM CSS
# ---------------------------------------------------
st.markdown("""
<style>
    .main {
        background-color: #f5f7ff;
    }

    .title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        color: #4B4DED;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #555;
        margin-bottom: 25px;
    }

    .question-box {
        background-color: white;
        padding: 25px;
        border-radius: 20px;
        box-shadow: 0px 5px 15px rgba(0,0,0,0.10);
        margin-bottom: 20px;
    }

    .score-box {
        background-color: #fff3cd;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
    }

    .level-box {
        background-color: #e8f5e9;
        padding: 10px;
        border-radius: 12px;
        text-align: center;
        font-weight: bold;
    }

    .footer {
        text-align: center;
        color: #777;
        margin-top: 30px;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# QUESTIONS
# ---------------------------------------------------
questions = [
    # EASY
    {
        "level": "🟢 Easy",
        "question": "Solve: x + 7 = 15",
        "answers": ["6", "7", "8", "9"],
        "correct": "8",
        "explanation": "Subtract 7 from both sides: x = 15 − 7 = 8."
    },
    {
        "level": "🟢 Easy",
        "question": "Solve: x − 5 = 12",
        "answers": ["15", "16", "17", "18"],
        "correct": "17",
        "explanation": "Add 5 to both sides: x = 12 + 5 = 17."
    },
    {
        "level": "🟢 Easy",
        "question": "Solve: 3x = 21",
        "answers": ["6", "7", "8", "9"],
        "correct": "7",
        "explanation": "Divide both sides by 3: x = 21 ÷ 3 = 7."
    },

    # MEDIUM
    {
        "level": "🟡 Medium",
        "question": "Solve: 2x + 5 = 17",
        "answers": ["5", "6", "7", "8"],
        "correct": "6",
        "explanation": "Subtract 5: 2x = 12. Divide by 2: x = 6."
    },
    {
        "level": "🟡 Medium",
        "question": "Solve: 4x − 3 = 21",
        "answers": ["5", "6", "7", "8"],
        "correct": "6",
        "explanation": "Add 3: 4x = 24. Divide by 4: x = 6."
    },
    {
        "level": "🟡 Medium",
        "question": "Solve: 5x + 10 = 35",
        "answers": ["4", "5", "6", "7"],
        "correct": "5",
        "explanation": "Subtract 10: 5x = 25. Divide by 5: x = 5."
    },

    # DIFFICULT
    {
        "level": "🔴 Difficult",
        "question": "Solve: 3(x + 2) = 21",
        "answers": ["4", "5", "6", "7"],
        "correct": "5",
        "explanation": "Divide by 3: x + 2 = 7. Subtract 2: x = 5."
    },
    {
        "level": "🔴 Difficult",
        "question": "Solve: 2(x − 4) = 16",
        "answers": ["10", "11", "12", "13"],
        "correct": "12",
        "explanation": "Divide by 2: x − 4 = 8. Add 4: x = 12."
    },
    {
        "level": "🔴 Difficult",
        "question": "Solve: 5x − 7 = 3x + 9",
        "answers": ["6", "7", "8", "9"],
        "correct": "8",
        "explanation": "Subtract 3x: 2x − 7 = 9. Add 7: 2x = 16. Divide by 2: x = 8."
    },
    {
        "level": "🔴 Difficult",
        "question": "Solve: 4(x + 1) = 2x + 18",
        "answers": ["6", "7", "8", "9"],
        "correct": "7",
        "explanation": "Expand: 4x + 4 = 2x + 18. Therefore 2x = 14, so x = 7."
    }
]

# ---------------------------------------------------
# SESSION STATE
# ---------------------------------------------------
if "started" not in st.session_state:
    st.session_state.started = False

if "questions" not in st.session_state:
    st.session_state.questions = questions.copy()

if "current" not in st.session_state:
    st.session_state.current = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected" not in st.session_state:
    st.session_state.selected = None

# ---------------------------------------------------
# START SCREEN
# ---------------------------------------------------
if not st.session_state.started:

    st.markdown(
        '<div class="title">🧮 EQUATION QUEST</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">🎮 Grade 7 Mathematics Adventure</div>',
        unsafe_allow_html=True
    )

    st.image(
        "https://images.unsplash.com/photo-1509228468518-180dd4864904",
        caption="Ready to become an Equation Master?",
        use_container_width=True
    )

    st.markdown("### 🌟 Your Mission")

    st.write("""
    Welcome, young mathematician! 🚀

    Your mission is to solve **10 equations** and become an
    **Equation Master**.

    You will face:
    - 🟢 Easy equations
    - 🟡 Medium equations
    - 🔴 Difficult equations

    Choose the correct answer and earn points!
    """)

    if st.button("🚀 START GAME", use_container_width=True):
        st.session_state.started = True
        st.rerun()

# ---------------------------------------------------
# GAME SCREEN
# ---------------------------------------------------
else:

    total = len(st.session_state.questions)
    current = st.session_state.current

    # Game finished
    if current >= total:

        st.balloons()

        percentage = (st.session_state.score / total) * 100

        st.markdown(
            '<div class="title">🏆 GAME COMPLETE!</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            f"""
            <div class="score-box">
                ⭐ Your Score: {st.session_state.score} / {total}
                <br>
                📊 Percentage: {percentage:.0f}%
            </div>
            """,
            unsafe_allow_html=True
        )

        if percentage == 100:
            st.success("🌟 PERFECT! You are an Equation Master!")
        elif percentage >= 80:
            st.success("🎉 Excellent work! You are very good at equations!")
        elif percentage >= 60:
            st.info("👍 Good job! Keep practicing!")
        else:
            st.warning("💪 Don't give up! Practice makes perfect!")

        st.markdown("### 📚 What did you practice?")
        st.write("""
        ✔ One-step equations
        ✔ Two-step equations
        ✔ Equations with brackets
        ✔ Equations with variables on both sides
        """)

        if st.button("🔄 PLAY AGAIN", use_container_width=True):
            st.session_state.started = False
            st.session_state.current = 0
            st.session_state.score = 0
            st.session_state.answered = False
            st.session_state.selected = None
            st.rerun()

    # Question screen
    else:

        q = st.session_state.questions[current]

        # Header
        st.markdown(
            '<div class="title">🧮 EQUATION QUEST</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            '<div class="subtitle">Can you solve the equation?</div>',
            unsafe_allow_html=True
        )

        # Score
        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "⭐ Score",
                st.session_state.score
            )

        with col2:
            st.metric(
                "📝 Question",
                f"{current + 1}/{total}"
            )

        # Progress
        st.progress(
            (current + 1) / total
        )

        # Level
        st.markdown(
            f'<div class="level-box">{q["level"]}</div>',
            unsafe_allow_html=True
        )

        st.write("")

        # Question box
        st.markdown(
            f"""
            <div class="question-box">
                <h2 style="text-align:center;">
                    ❓ {q["question"]}
                </h2>
            </div>
            """,
            unsafe_allow_html=True
        )

        # Answer buttons
        for answer in q["answers"]:

            if st.button(
                f"🔢 {answer}",
                key=f"answer_{current}_{answer}",
                use_container_width=True
            ):

                if not st.session_state.answered:

                    st.session_state.selected = answer
                    st.session_state.answered = True

                    if answer == q["correct"]:
                        st.session_state.score += 1

                    st.rerun()

        # Feedback
        if st.session_state.answered:

            if st.session_state.selected == q["correct"]:

                st.success(
                    f"🎉 Correct! The answer is {q['correct']}."
                )

            else:

                st.error(
                    f"❌ Not quite! The correct answer is "
                    f"{q['correct']}."
                )

            st.info(
                f"💡 Explanation: {q['explanation']}"
            )

            if st.button(
                "➡️ NEXT QUESTION",
                use_container_width=True
            ):

                st.session_state.current += 1
                st.session_state.answered = False
                st.session_state.selected = None
                st.rerun()

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------
st.markdown(
    '<div class="footer">🌱 Learn • Practice • Play • Master Mathematics 🧮</div>',
    unsafe_allow_html=True
)
```

## 2. Create `requirements.txt`

Create another file called **`requirements.txt`**:

```text
streamlit
```

## 3. Test the game on your computer

Open Command Prompt/Terminal in the folder containing `app.py`:

```bash
pip install streamlit
```

Then run:

```bash
streamlit run app.py
```

Your browser should open the game automatically.

---

# 🚀 Deploy to Streamlit

The easiest method is:

### Step 1 — Create a GitHub repository

Go to [GitHub](https://github.com/?utm_source=chatgpt.com) and create a new repository, for example:

```text
grade7-equation-game
```

Upload these two files:

```text
grade7-equation-game/
│
├── app.py
└── requirements.txt
```

### Step 2 — Deploy

Go to [Streamlit Community Cloud](https://share.streamlit.io/?utm_source=chatgpt.com) and sign in with GitHub.

Choose:

**Create app → Deploy a public app**

Then select:

```text
Repository: grade7-equation-game
Branch: main
Main file path: app.py
```

Click **Deploy**.

After deployment, Streamlit will give you a link that you can share with your students.

### 💡 Recommended next upgrade

For a **much more attractive Grade 7 classroom game**, I can also make a version with **levels, lives ❤️, coins 🪙, timer ⏱️, sound effects 🔊, character/avatar selection, 20 questions, randomized equations, and a leaderboard 🏆**, still using only **Python + Streamlit**.