# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KeqqTEhS7qPmHDNg1LWnV-raEQ2nfxq
"""

Absolutely! For **Grade 1**, I recommend a colorful, simple game with big buttons, sounds/emoji, rewards, and very easy math.

### 🎮 Game idea: **Math Adventure – Catch the Stars ⭐**

Students answer simple questions such as:

* 🔢 Counting numbers
* ➕ Addition within 10
* ➖ Subtraction within 10
* 🔍 Which number is bigger?
* 🧩 Missing numbers

The game can have **3 levels**:

1. 🌱 **Easy** – Counting & number recognition
2. 🚀 **Medium** – Addition and subtraction
3. 🏆 **Challenge** – Mixed questions

Here is a complete **Streamlit + Python** version you can use:

```python
import streamlit as st
import random

# -----------------------------
# PAGE CONFIGURATION
# -----------------------------
st.set_page_config(
    page_title="Math Adventure ⭐",
    page_icon="⭐",
    layout="centered"
)

# -----------------------------
# CUSTOM CSS
# -----------------------------
st.markdown("""
<style>
.main {
    background-color: #FFF8E7;
}

.big-title {
    font-size: 45px;
    font-weight: bold;
    text-align: center;
}

.subtitle {
    font-size: 22px;
    text-align: center;
}

.question {
    font-size: 38px;
    font-weight: bold;
    text-align: center;
    padding: 20px;
}

.score {
    font-size: 25px;
    font-weight: bold;
    text-align: center;
}

.stButton > button {
    width: 100%;
    height: 60px;
    font-size: 25px;
    border-radius: 15px;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# SESSION STATE
# -----------------------------
if "score" not in st.session_state:
    st.session_state.score = 0

if "question" not in st.session_state:
    st.session_state.question = None

if "answer" not in st.session_state:
    st.session_state.answer = None

if "options" not in st.session_state:
    st.session_state.options = []

if "question_number" not in st.session_state:
    st.session_state.question_number = 0

if "game_started" not in st.session_state:
    st.session_state.game_started = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "level" not in st.session_state:
    st.session_state.level = "🌱 Easy"


# -----------------------------
# QUESTION GENERATOR
# -----------------------------
def generate_question(level):

    if level == "🌱 Easy":

        question_type = random.choice([
            "count",
            "bigger",
            "missing"
        ])

        if question_type == "count":

            number = random.randint(1, 10)

            question = f"⭐ " * number
            answer = number

            options = list(range(1, 11))
            random.shuffle(options)
            options = options[:4]

            if answer not in options:
                options[0] = answer

            random.shuffle(options)

            return question, answer, options

        elif question_type == "bigger":

            a = random.randint(1, 10)
            b = random.randint(1, 10)

            answer = max(a, b)

            question = f"Which number is BIGGER?\n\n🔵 {a} or 🔴 {b}?"

            options = [a, b]

            return question, answer, options

        else:

            a = random.randint(1, 8)
            answer = a + 1

            question = f"What number comes next?\n\n🔢 {a}, ___"

            options = [
                answer,
                answer + 1,
                answer - 1,
                answer + 2
            ]

            options = list(set(options))

            return question, answer, options

    elif level == "🚀 Medium":

        operation = random.choice(["addition", "subtraction"])

        if operation == "addition":

            a = random.randint(1, 5)
            b = random.randint(1, 5)

            answer = a + b

            question = f"🍎 {a} + 🍎 {b} = ?"

        else:

            a = random.randint(3, 10)
            b = random.randint(1, a)

            answer = a - b

            question = f"🍎 {a} - 🍎 {b} = ?"

        options = [
            answer,
            answer + 1,
            max(0, answer - 1),
            answer + 2
        ]

        options = list(set(options))

        return question, answer, options

    else:

        operation = random.choice([
            "addition",
            "subtraction",
            "missing"
        ])

        if operation == "addition":

            a = random.randint(1, 9)
            b = random.randint(1, 9)

            answer = a + b

            question = f"🚀 {a} + {b} = ?"

        elif operation == "subtraction":

            a = random.randint(5, 15)
            b = random.randint(1, a)

            answer = a - b

            question = f"🚀 {a} - {b} = ?"

        else:

            a = random.randint(1, 9)
            answer = a + 2

            question = f"🧩 {a}, {a+1}, ___, {a+3}"

        options = [
            answer,
            answer + 1,
            max(0, answer - 1),
            answer + 2
        ]

        options = list(set(options))

        return question, answer, options


# -----------------------------
# NEW QUESTION
# -----------------------------
def new_question():

    q, ans, opts = generate_question(
        st.session_state.level
    )

    st.session_state.question = q
    st.session_state.answer = ans
    st.session_state.options = opts
    st.session_state.feedback = ""

    st.session_state.question_number += 1


# -----------------------------
# TITLE
# -----------------------------
st.markdown(
    '<div class="big-title">⭐ Math Adventure ⭐</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎮 Learn Math • Play • Win Stars!</div>',
    unsafe_allow_html=True
)

st.write("")


# -----------------------------
# START SCREEN
# -----------------------------
if not st.session_state.game_started:

    st.markdown("### 👋 Hello, Math Explorer!")

    st.write(
        "Welcome to your math adventure! "
        "Answer questions and collect stars ⭐."
    )

    st.markdown("### 🎯 Choose Your Level")

    level = st.selectbox(
        "Level",
        [
            "🌱 Easy",
            "🚀 Medium",
            "🏆 Challenge"
        ]
    )

    st.session_state.level = level

    if st.button("🎮 START GAME!"):

        st.session_state.game_started = True
        st.session_state.score = 0
        st.session_state.question_number = 0

        new_question()

        st.rerun()


# -----------------------------
# GAME SCREEN
# -----------------------------
else:

    # Score
    st.markdown(
        f'<div class="score">'
        f'⭐ Stars: {st.session_state.score}'
        f'</div>',
        unsafe_allow_html=True
    )

    st.write("")

    st.progress(
        min(
            st.session_state.question_number / 10,
            1.0
        )
    )

    st.write(
        f"Question {st.session_state.question_number} of 10"
    )

    # Question
    st.markdown(
        f'<div class="question">'
        f'{st.session_state.question}'
        f'</div>',
        unsafe_allow_html=True
    )

    st.write("")

    # Answer buttons
    options = st.session_state.options

    random.shuffle(options)

    columns = st.columns(2)

    for i, option in enumerate(options):

        with columns[i % 2]:

            if st.button(
                f"⭐ {option}",
                key=f"answer_{st.session_state.question_number}_{i}"
            ):

                if option == st.session_state.answer:

                    st.session_state.score += 1

                    st.session_state.feedback = (
                        "🎉 AMAZING! Correct! ⭐⭐⭐"
                    )

                else:

                    st.session_state.feedback = (
                        f"😊 Good try! "
                        f"The answer is "
                        f"{st.session_state.answer}."
                    )

    # Feedback
    if st.session_state.feedback:

        st.success(st.session_state.feedback)

        if st.session_state.question_number < 10:

            if st.button("➡️ NEXT QUESTION"):

                new_question()

                st.rerun()

        else:

            st.balloons()

            st.markdown("## 🏆 GAME COMPLETE!")

            st.markdown(
                f"### You collected "
                f"**{st.session_state.score} ⭐ stars!**"
            )

            if st.session_state.score == 10:

                st.success(
                    "🌟 SUPER MATH CHAMPION! 🌟"
                )

            elif st.session_state.score >= 7:

                st.success(
                    "🎉 Great job, Math Explorer!"
                )

            else:

                st.info(
                    "💪 Keep practicing! "
                    "You are getting better!"
                )

            if st.button("🔄 PLAY AGAIN"):

                st.session_state.game_started = False
                st.session_state.score = 0
                st.session_state.question_number = 0
                st.session_state.feedback = ""

                st.rerun()

    # Exit
    st.write("")

    if st.button("🏠 Back to Menu"):

        st.session_state.game_started = False
        st.session_state.question = None
        st.session_state.feedback = ""

        st.rerun()
```

### 🚀 How to deploy it on Streamlit

Create a file called:

```text
app.py
```

Then install Streamlit:

```bash
pip install streamlit
```

Run it:

```bash
streamlit run app.py
```

For your Grade 1 students, I would make the next version even more attractive by adding **🎵 sound effects, 🐰 animated characters, ❤️ lives, ⭐ star collection, 🏆 levels, and a colorful “Math World” map**.

Absolutely! For **Grade 1**, I recommend a colorful, simple game with big buttons, sounds/emoji, rewards, and very easy math.

### 🎮 Game idea: **Math Adventure – Catch the Stars ⭐**

Students answer simple questions such as:

* 🔢 Counting numbers
* ➕ Addition within 10
* ➖ Subtraction within 10
* 🔍 Which number is bigger?
* 🧩 Missing numbers

The game can have **3 levels**:

1. 🌱 **Easy** – Counting & number recognition
2. 🚀 **Medium** – Addition and subtraction
3. 🏆 **Challenge** – Mixed questions

Here is a complete **Streamlit + Python** version you can use:

```python
import streamlit as st
import random

# -----------------------------
# PAGE CONFIGURATION
# -----------------------------
st.set_page_config(
    page_title="Math Adventure ⭐",
    page_icon="⭐",
    layout="centered"
)

# -----------------------------
# CUSTOM CSS
# -----------------------------
st.markdown("""
<style>
.main {
    background-color: #FFF8E7;
}

.big-title {
    font-size: 45px;
    font-weight: bold;
    text-align: center;
}

.subtitle {
    font-size: 22px;
    text-align: center;
}

.question {
    font-size: 38px;
    font-weight: bold;
    text-align: center;
    padding: 20px;
}

.score {
    font-size: 25px;
    font-weight: bold;
    text-align: center;
}

.stButton > button {
    width: 100%;
    height: 60px;
    font-size: 25px;
    border-radius: 15px;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# SESSION STATE
# -----------------------------
if "score" not in st.session_state:
    st.session_state.score = 0

if "question" not in st.session_state:
    st.session_state.question = None

if "answer" not in st.session_state:
    st.session_state.answer = None

if "options" not in st.session_state:
    st.session_state.options = []

if "question_number" not in st.session_state:
    st.session_state.question_number = 0

if "game_started" not in st.session_state:
    st.session_state.game_started = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "level" not in st.session_state:
    st.session_state.level = "🌱 Easy"


# -----------------------------
# QUESTION GENERATOR
# -----------------------------
def generate_question(level):

    if level == "🌱 Easy":

        question_type = random.choice([
            "count",
            "bigger",
            "missing"
        ])

        if question_type == "count":

            number = random.randint(1, 10)

            question = f"⭐ " * number
            answer = number

            options = list(range(1, 11))
            random.shuffle(options)
            options = options[:4]

            if answer not in options:
                options[0] = answer

            random.shuffle(options)

            return question, answer, options

        elif question_type == "bigger":

            a = random.randint(1, 10)
            b = random.randint(1, 10)

            answer = max(a, b)

            question = f"Which number is BIGGER?\n\n🔵 {a} or 🔴 {b}?"

            options = [a, b]

            return question, answer, options

        else:

            a = random.randint(1, 8)
            answer = a + 1

            question = f"What number comes next?\n\n🔢 {a}, ___"

            options = [
                answer,
                answer + 1,
                answer - 1,
                answer + 2
            ]

            options = list(set(options))

            return question, answer, options

    elif level == "🚀 Medium":

        operation = random.choice(["addition", "subtraction"])

        if operation == "addition":

            a = random.randint(1, 5)
            b = random.randint(1, 5)

            answer = a + b

            question = f"🍎 {a} + 🍎 {b} = ?"

        else:

            a = random.randint(3, 10)
            b = random.randint(1, a)

            answer = a - b

            question = f"🍎 {a} - 🍎 {b} = ?"

        options = [
            answer,
            answer + 1,
            max(0, answer - 1),
            answer + 2
        ]

        options = list(set(options))

        return question, answer, options

    else:

        operation = random.choice([
            "addition",
            "subtraction",
            "missing"
        ])

        if operation == "addition":

            a = random.randint(1, 9)
            b = random.randint(1, 9)

            answer = a + b

            question = f"🚀 {a} + {b} = ?"

        elif operation == "subtraction":

            a = random.randint(5, 15)
            b = random.randint(1, a)

            answer = a - b

            question = f"🚀 {a} - {b} = ?"

        else:

            a = random.randint(1, 9)
            answer = a + 2

            question = f"🧩 {a}, {a+1}, ___, {a+3}"

        options = [
            answer,
            answer + 1,
            max(0, answer - 1),
            answer + 2
        ]

        options = list(set(options))

        return question, answer, options


# -----------------------------
# NEW QUESTION
# -----------------------------
def new_question():

    q, ans, opts = generate_question(
        st.session_state.level
    )

    st.session_state.question = q
    st.session_state.answer = ans
    st.session_state.options = opts
    st.session_state.feedback = ""

    st.session_state.question_number += 1


# -----------------------------
# TITLE
# -----------------------------
st.markdown(
    '<div class="big-title">⭐ Math Adventure ⭐</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎮 Learn Math • Play • Win Stars!</div>',
    unsafe_allow_html=True
)

st.write("")


# -----------------------------
# START SCREEN
# -----------------------------
if not st.session_state.game_started:

    st.markdown("### 👋 Hello, Math Explorer!")

    st.write(
        "Welcome to your math adventure! "
        "Answer questions and collect stars ⭐."
    )

    st.markdown("### 🎯 Choose Your Level")

    level = st.selectbox(
        "Level",
        [
            "🌱 Easy",
            "🚀 Medium",
            "🏆 Challenge"
        ]
    )

    st.session_state.level = level

    if st.button("🎮 START GAME!"):

        st.session_state.game_started = True
        st.session_state.score = 0
        st.session_state.question_number = 0

        new_question()

        st.rerun()


# -----------------------------
# GAME SCREEN
# -----------------------------
else:

    # Score
    st.markdown(
        f'<div class="score">'
        f'⭐ Stars: {st.session_state.score}'
        f'</div>',
        unsafe_allow_html=True
    )

    st.write("")

    st.progress(
        min(
            st.session_state.question_number / 10,
            1.0
        )
    )

    st.write(
        f"Question {st.session_state.question_number} of 10"
    )

    # Question
    st.markdown(
        f'<div class="question">'
        f'{st.session_state.question}'
        f'</div>',
        unsafe_allow_html=True
    )

    st.write("")

    # Answer buttons
    options = st.session_state.options

    random.shuffle(options)

    columns = st.columns(2)

    for i, option in enumerate(options):

        with columns[i % 2]:

            if st.button(
                f"⭐ {option}",
                key=f"answer_{st.session_state.question_number}_{i}"
            ):

                if option == st.session_state.answer:

                    st.session_state.score += 1

                    st.session_state.feedback = (
                        "🎉 AMAZING! Correct! ⭐⭐⭐"
                    )

                else:

                    st.session_state.feedback = (
                        f"😊 Good try! "
                        f"The answer is "
                        f"{st.session_state.answer}."
                    )

    # Feedback
    if st.session_state.feedback:

        st.success(st.session_state.feedback)

        if st.session_state.question_number < 10:

            if st.button("➡️ NEXT QUESTION"):

                new_question()

                st.rerun()

        else:

            st.balloons()

            st.markdown("## 🏆 GAME COMPLETE!")

            st.markdown(
                f"### You collected "
                f"**{st.session_state.score} ⭐ stars!**"
            )

            if st.session_state.score == 10:

                st.success(
                    "🌟 SUPER MATH CHAMPION! 🌟"
                )

            elif st.session_state.score >= 7:

                st.success(
                    "🎉 Great job, Math Explorer!"
                )

            else:

                st.info(
                    "💪 Keep practicing! "
                    "You are getting better!"
                )

            if st.button("🔄 PLAY AGAIN"):

                st.session_state.game_started = False
                st.session_state.score = 0
                st.session_state.question_number = 0
                st.session_state.feedback = ""

                st.rerun()

    # Exit
    st.write("")

    if st.button("🏠 Back to Menu"):

        st.session_state.game_started = False
        st.session_state.question = None
        st.session_state.feedback = ""

        st.rerun()
```

### 🚀 How to deploy it on Streamlit

Create a file called:

```text
app.py
```

Then install Streamlit:

```bash
pip install streamlit
```

Run it:

```bash
streamlit run app.py
```

For your Grade 1 students, I would make the next version even more attractive by adding **🎵 sound effects, 🐰 animated characters, ❤️ lives, ⭐ star collection, 🏆 levels, and a colorful “Math World” map**.