# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sL3ygemr9qd0L_XWxef0TyUVsTwQ5PLX
"""

import streamlit as st
import random

# --------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------
st.set_page_config(
    page_title="Geometry Quest - Grade 7",
    page_icon="📐",
    layout="centered"
)

# --------------------------------------------------
# CUSTOM CSS
# --------------------------------------------------
st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #e0f7fa, #fff3e0);
    }

    .title {
        text-align: center;
        font-size: 45px;
        font-weight: bold;
        color: #1565C0;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #555;
    }

    .question-box {
        background-color: white;
        padding: 25px;
        border-radius: 20px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.15);
        margin-bottom: 20px;
    }

    .score-box {
        background-color: #fff8e1;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
    }

    .correct {
        background-color: #c8e6c9;
        padding: 15px;
        border-radius: 15px;
        color: #1b5e20;
        font-weight: bold;
    }

    .wrong {
        background-color: #ffcdd2;
        padding: 15px;
        border-radius: 15px;
        color: #b71c1c;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# QUESTIONS
# --------------------------------------------------
QUESTIONS = [
    {
        "question": "📐 An angle measures 90°. What type of angle is it?",
        "options": ["Acute angle", "Right angle", "Obtuse angle", "Reflex angle"],
        "answer": "Right angle",
        "explanation": "A right angle measures exactly 90°.",
        "level": "Easy"
    },
    {
        "question": "🔺 A triangle has angles 50° and 60°. What is the third angle?",
        "options": ["60°", "70°", "80°", "90°"],
        "answer": "70°",
        "explanation": "Angles in a triangle add up to 180°. 180° − 50° − 60° = 70°.",
        "level": "Easy"
    },
    {
        "question": "📏 A rectangle has a length of 12 cm and width of 5 cm. What is its perimeter?",
        "options": ["17 cm", "24 cm", "34 cm", "60 cm"],
        "answer": "34 cm",
        "explanation": "Perimeter = 2 × (length + width) = 2 × (12 + 5) = 34 cm.",
        "level": "Easy"
    },
    {
        "question": "⬛ What is the area of a square with a side length of 8 cm?",
        "options": ["16 cm²", "32 cm²", "64 cm²", "128 cm²"],
        "answer": "64 cm²",
        "explanation": "Area of a square = side × side = 8 × 8 = 64 cm².",
        "level": "Easy"
    },
    {
        "question": "🔺 A triangle has a base of 10 cm and height of 6 cm. What is its area?",
        "options": ["16 cm²", "30 cm²", "60 cm²", "120 cm²"],
        "answer": "30 cm²",
        "explanation": "Area = ½ × base × height = ½ × 10 × 6 = 30 cm².",
        "level": "Medium"
    },
    {
        "question": "📐 Two angles are supplementary. One angle is 125°. What is the other angle?",
        "options": ["45°", "55°", "65°", "75°"],
        "answer": "55°",
        "explanation": "Supplementary angles add up to 180°. 180° − 125° = 55°.",
        "level": "Medium"
    },
    {
        "question": "🔷 A parallelogram has a base of 14 cm and height of 7 cm. What is its area?",
        "options": ["21 cm²", "42 cm²", "98 cm²", "196 cm²"],
        "answer": "98 cm²",
        "explanation": "Area = base × height = 14 × 7 = 98 cm².",
        "level": "Medium"
    },
    {
        "question": "🔺 An isosceles triangle has two equal angles of 70°. What is the third angle?",
        "options": ["30°", "40°", "50°", "60°"],
        "answer": "40°",
        "explanation": "180° − 70° − 70° = 40°.",
        "level": "Medium"
    },
    {
        "question": "🧩 A regular hexagon has 6 equal sides. What is the sum of its interior angles?",
        "options": ["360°", "540°", "720°", "900°"],
        "answer": "720°",
        "explanation": "Interior angle sum = (n − 2) × 180°. For a hexagon: (6 − 2) × 180° = 720°.",
        "level": "Hard"
    },
    {
        "question": "📐 Two parallel lines are cut by a transversal. If one corresponding angle is 65°, what is the other corresponding angle?",
        "options": ["25°", "65°", "115°", "125°"],
        "answer": "65°",
        "explanation": "Corresponding angles between parallel lines are equal.",
        "level": "Hard"
    },
    {
        "question": "🔺 A triangle has sides 6 cm, 8 cm, and 10 cm. What type of triangle is it?",
        "options": [
            "Equilateral",
            "Isosceles",
            "Right-angled",
            "Obtuse"
        ],
        "answer": "Right-angled",
        "explanation": "6² + 8² = 10², so it satisfies the Pythagorean theorem.",
        "level": "Hard"
    },
    {
        "question": "🏠 A rectangular garden is 20 m long and 12 m wide. A path surrounds it. What is the perimeter of the garden?",
        "options": ["32 m", "64 m", "120 m", "240 m"],
        "answer": "64 m",
        "explanation": "Perimeter = 2 × (20 + 12) = 64 m.",
        "level": "Hard"
    }
]

# --------------------------------------------------
# SESSION STATE
# --------------------------------------------------
if "started" not in st.session_state:
    st.session_state.started = False

if "questions" not in st.session_state:
    st.session_state.questions = []

if "current" not in st.session_state:
    st.session_state.current = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "lives" not in st.session_state:
    st.session_state.lives = 3

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected_answer" not in st.session_state:
    st.session_state.selected_answer = None

# --------------------------------------------------
# START SCREEN
# --------------------------------------------------
if not st.session_state.started:

    st.markdown(
        '<div class="title">📐 GEOMETRY QUEST</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">🎮 Grade 7 Mathematics Adventure</div>',
        unsafe_allow_html=True
    )

    st.write("")

    st.markdown("""
    ### 🏆 Your Mission

    Become a **Geometry Master** by solving geometry challenges!

    You will face questions about:

    🔹 Angles
    🔹 Triangles
    🔹 Quadrilaterals
    🔹 Perimeter
    🔹 Area
    🔹 Geometric reasoning

    ### ❤️ You have 3 lives

    ⭐ Easy = +10 points
    ⭐ Medium = +20 points
    ⭐ Hard = +30 points
    """)

    if st.button("🚀 START GEOMETRY QUEST", use_container_width=True):

        st.session_state.started = True
        st.session_state.questions = random.sample(QUESTIONS, len(QUESTIONS))
        st.session_state.current = 0
        st.session_state.score = 0
        st.session_state.lives = 3
        st.session_state.answered = False

        st.rerun()

# --------------------------------------------------
# GAME SCREEN
# --------------------------------------------------
else:

    questions = st.session_state.questions
    current = st.session_state.current

    # GAME OVER
    if current >= len(questions) or st.session_state.lives <= 0:

        st.markdown(
            '<div class="title">🏆 QUEST COMPLETE!</div>',
            unsafe_allow_html=True
        )

        st.write("")

        score = st.session_state.score

        st.metric(
            "🎯 FINAL SCORE",
            f"{score} points"
        )

        if score >= 250:
            st.success("🌟 AMAZING! You are a Geometry Master!")
        elif score >= 150:
            st.info("👏 GREAT JOB! Your geometry skills are strong!")
        elif score >= 80:
            st.warning("👍 GOOD TRY! Keep practicing geometry!")
        else:
            st.error("💪 Don't give up! Practice makes progress!")

        st.write("")

        if st.button("🔄 PLAY AGAIN", use_container_width=True):

            st.session_state.started = False
            st.session_state.questions = []
            st.session_state.current = 0
            st.session_state.score = 0
            st.session_state.lives = 3
            st.session_state.answered = False

            st.rerun()

    # QUESTION SCREEN
    else:

        q = questions[current]

        # HEADER
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("🎯 Score", st.session_state.score)

        with col2:
            st.metric(
                "❤️ Lives",
                st.session_state.lives
            )

        with col3:
            st.metric(
                "📚 Question",
                f"{current + 1}/{len(questions)}"
            )

        # PROGRESS
        progress = current / len(questions)

        st.progress(progress)

        st.write("")

        # QUESTION
        st.markdown(
            f"""
            <div class="question-box">
                <h2>{q["question"]}</h2>
                <p><b>Level:</b> {q["level"]}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        # ANSWER BUTTONS
        if not st.session_state.answered:

            for option in q["options"]:

                if st.button(
                    option,
                    key=f"{current}_{option}",
                    use_container_width=True
                ):

                    st.session_state.selected_answer = option
                    st.session_state.answered = True

                    if option == q["answer"]:

                        if q["level"] == "Easy":
                            st.session_state.score += 10
                        elif q["level"] == "Medium":
                            st.session_state.score += 20
                        else:
                            st.session_state.score += 30

                    else:
                        st.session_state.lives -= 1

                    st.rerun()

        # FEEDBACK
        else:

            selected = st.session_state.selected_answer

            if selected == q["answer"]:

                st.markdown(
                    f"""
                    <div class="correct">
                    🎉 CORRECT!<br><br>
                    {q["explanation"]}
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            else:

                st.markdown(
                    f"""
                    <div class="wrong">
                    ❌ NOT QUITE!<br><br>
                    Correct answer: <b>{q["answer"]}</b><br><br>
                    {q["explanation"]}
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            st.write("")

            if st.button(
                "➡️ NEXT CHALLENGE",
                use_container_width=True
            ):

                st.session_state.current += 1
                st.session_state.answered = False
                st.session_state.selected_answer = None

                st.rerun()

        # SIDEBAR
        with st.sidebar:

            st.header("📐 Geometry Quest")

            st.write("### 🏆 Scoring")

            st.write("🟢 Easy: +10")
            st.write("🟡 Medium: +20")
            st.write("🔴 Hard: +30")

            st.write("---")

            st.write("### ❤️ Lives")

            for i in range(st.session_state.lives):
                st.write("❤️", end="")

            st.write("")

            st.write("---")

            st.write("### 💡 Geometry Tip")

            st.info(
                "Remember: the angles inside a triangle always add up to 180°!"
            )