# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIyP6p2ec156KAoITb0smfgz1-J8FctQ
"""

import streamlit as st
import random

# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Sequence Master - Grade 7",
    page_icon="🔢",
    layout="centered"
)

# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #667eea, #764ba2);
    }

    .game-title {
        text-align: center;
        font-size: 45px;
        font-weight: bold;
        color: #4B0082;
        margin-bottom: 0px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #555555;
        margin-bottom: 25px;
    }

    .question-box {
        background-color: #F5F0FF;
        padding: 25px;
        border-radius: 20px;
        border: 3px solid #8A2BE2;
        text-align: center;
        margin: 15px 0px;
    }

    .sequence {
        font-size: 30px;
        font-weight: bold;
        color: #4B0082;
        letter-spacing: 5px;
    }

    .score-box {
        background-color: #FFF3CD;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
    }

    .streak-box {
        background-color: #D4EDDA;
        padding: 12px;
        border-radius: 15px;
        text-align: center;
        font-size: 20px;
    }

    .result-box {
        padding: 30px;
        border-radius: 20px;
        text-align: center;
        background-color: #E8F4FF;
        border: 3px solid #2196F3;
    }
</style>
""", unsafe_allow_html=True)


# ============================================================
# QUESTION DATABASE
# ============================================================

questions = [

    # ---------------- EASY ----------------

    {
        "level": "Easy",
        "sequence": [2, 4, 6, 8, "?"],
        "answer": 10,
        "hint": "Look at how much the numbers increase.",
        "explanation": "Each number increases by 2."
    },

    {
        "level": "Easy",
        "sequence": [5, 10, 15, 20, "?"],
        "answer": 25,
        "hint": "The same number is added each time.",
        "explanation": "Each number increases by 5."
    },

    {
        "level": "Easy",
        "sequence": [10, 20, 30, 40, "?"],
        "answer": 50,
        "hint": "Add the same number each time.",
        "explanation": "Each number increases by 10."
    },

    {
        "level": "Easy",
        "sequence": [3, 6, 9, 12, "?"],
        "answer": 15,
        "hint": "Think about multiples of 3.",
        "explanation": "Each number increases by 3."
    },

    # ---------------- MEDIUM ----------------

    {
        "level": "Medium",
        "sequence": [4, 8, 16, 32, "?"],
        "answer": 64,
        "hint": "Try multiplying instead of adding.",
        "explanation": "Each number is multiplied by 2."
    },

    {
        "level": "Medium",
        "sequence": [100, 90, 80, 70, "?"],
        "answer": 60,
        "hint": "The sequence is decreasing.",
        "explanation": "Each number decreases by 10."
    },

    {
        "level": "Medium",
        "sequence": [1, 4, 9, 16, "?"],
        "answer": 25,
        "hint": "Think of square numbers.",
        "explanation": "These are 1², 2², 3², 4², 5²."
    },

    # ---------------- HARD ----------------

    {
        "level": "Hard",
        "sequence": [2, 5, 10, 17, "?"],
        "answer": 26,
        "hint": "Look at the differences between terms.",
        "explanation": "Differences are +3, +5, +7, +9."
    },

    {
        "level": "Hard",
        "sequence": [3, 6, 12, 24, "?"],
        "answer": 48,
        "hint": "Check the multiplication pattern.",
        "explanation": "Each number is multiplied by 2."
    },

    {
        "level": "Hard",
        "sequence": [1, 1, 2, 3, 5, "?"],
        "answer": 8,
        "hint": "Add the previous two numbers.",
        "explanation": "This is the Fibonacci pattern."
    }
]


# ============================================================
# INITIALIZE GAME
# ============================================================

if "started" not in st.session_state:
    st.session_state.started = False

if "question" not in st.session_state:
    st.session_state.question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "streak" not in st.session_state:
    st.session_state.streak = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected_answer" not in st.session_state:
    st.session_state.selected_answer = None


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="game-title">🔢 SEQUENCE MASTER</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎯 Grade 7 Mathematics Challenge</div>',
    unsafe_allow_html=True
)


# ============================================================
# START SCREEN
# ============================================================

if not st.session_state.started:

    st.markdown("## 🚀 Welcome, Sequence Master!")

    st.write(
        """
        Your mission is to discover the **hidden pattern** in each
        number sequence.
        """
    )

    st.markdown("""
    ### 🎮 How to Play

    1. Look carefully at the sequence.
    2. Find the mathematical pattern.
    3. Choose the missing number.
    4. Get points for correct answers.
    5. Build your 🔥 streak!
    6. Try to become the **Sequence Master!**
    """)

    st.info("💡 Tip: Check whether the numbers are being added, subtracted, multiplied, or divided.")

    if st.button("🚀 START GAME", use_container_width=True):

        random.shuffle(questions)

        st.session_state.started = True
        st.session_state.question = 0
        st.session_state.score = 0
        st.session_state.streak = 0
        st.session_state.answered = False

        st.rerun()

    st.stop()


# ============================================================
# GAME COMPLETED
# ============================================================

if st.session_state.question >= len(questions):

    percentage = int(
        st.session_state.score /
        (len(questions) * 20) * 100
    )

    st.balloons()

    st.markdown("""
    <div class="result-box">
        <h1>🏆 GAME COMPLETE!</h1>
        <h2>You are a Sequence Master! 🎉</h2>
    </div>
    """, unsafe_allow_html=True)

    st.write("")

    st.metric(
        "⭐ Final Score",
        f"{st.session_state.score} points"
    )

    st.metric(
        "📊 Performance",
        f"{percentage}%"
    )

    if percentage >= 80:
        st.success("🌟 Excellent! You have mastered number sequences!")

    elif percentage >= 60:
        st.info("👏 Good job! Keep practicing sequences!")

    else:
        st.warning("💪 Keep practicing. You will become a Sequence Master!")

    if st.button("🔄 PLAY AGAIN", use_container_width=True):

        random.shuffle(questions)

        st.session_state.question = 0
        st.session_state.score = 0
        st.session_state.streak = 0
        st.session_state.answered = False
        st.session_state.selected_answer = None

        st.rerun()

    st.stop()


# ============================================================
# CURRENT QUESTION
# ============================================================

q = questions[st.session_state.question]

question_number = st.session_state.question + 1
total_questions = len(questions)

# Progress
progress = question_number / total_questions

st.progress(progress)

# Information row
col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Question",
        f"{question_number}/{total_questions}"
    )

with col2:
    st.metric(
        "Score",
        st.session_state.score
    )

with col3:
    st.metric(
        "🔥 Streak",
        st.session_state.streak
    )


# ============================================================
# DIFFICULTY
# ============================================================

if q["level"] == "Easy":
    emoji = "🟢"
elif q["level"] == "Medium":
    emoji = "🟡"
else:
    emoji = "🔴"

st.markdown(
    f"### {emoji} {q['level']} Level"
)


# ============================================================
# DISPLAY SEQUENCE
# ============================================================

sequence_text = "   ".join(
    str(x) for x in q["sequence"]
)

st.markdown(
    f"""
    <div class="question-box">
        <p>🔍 Find the missing number:</p>
        <div class="sequence">
            {sequence_text}
        </div>
    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# CREATE ANSWER OPTIONS
# ============================================================

correct_answer = q["answer"]

options = {correct_answer}

while len(options) < 4:

    variation = random.choice([
        -1, 1, -2, 2, -3, 3, -5, 5, -10, 10
    ])

    new_answer = correct_answer + variation

    if new_answer > 0:
        options.add(new_answer)

options = list(options)
random.shuffle(options)


# ============================================================
# ANSWER BUTTONS
# ============================================================

if not st.session_state.answered:

    st.write("### 🤔 Choose your answer:")

    for i, option in enumerate(options):

        if st.button(
            f"🔢 {option}",
            key=f"answer_{question_number}_{i}",
            use_container_width=True
        ):

            st.session_state.selected_answer = option
            st.session_state.answered = True

            if option == correct_answer:

                st.session_state.streak += 1

                # Base points
                points = 10

                # Streak bonus
                if st.session_state.streak >= 3:
                    points += 5

                # Difficulty bonus
                if q["level"] == "Medium":
                    points += 5

                elif q["level"] == "Hard":
                    points += 10

                st.session_state.score += points

            else:
                st.session_state.streak = 0

            st.rerun()


# ============================================================
# FEEDBACK
# ============================================================

else:

    selected = st.session_state.selected_answer

    if selected == correct_answer:

        st.success(
            f"🎉 CORRECT! The answer is {correct_answer}!"
        )

        if st.session_state.streak >= 3:
            st.warning(
                f"🔥 AMAZING! {st.session_state.streak} correct answers in a row!"
            )

    else:

        st.error(
            f"❌ Not quite! The correct answer is {correct_answer}."
        )

    st.info(
        f"💡 **Explanation:** {q['explanation']}"
    )

    st.write("")

    if st.button(
        "➡️ NEXT QUESTION",
        use_container_width=True
    ):

        st.session_state.question += 1
        st.session_state.answered = False
        st.session_state.selected_answer = None

        st.rerun()


# ============================================================
# HINT
# ============================================================

with st.expander("💡 Need a Hint?"):

    st.write(q["hint"])


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.markdown(
    "<center>📚 Grade 7 Mathematics | 🔢 Sequence Master | "
    "Learn • Think • Play • Master</center>",
    unsafe_allow_html=True
)