# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CX4IF_VtmmC1UNsYyBCyeoo0mwQXlRVq
"""

# ============================================================
# JOGO DE MATEMÁTICA: PRISMAS E PIRÂMIDES
# Python + Streamlit
# ============================================================

import streamlit as st
import math
import random

# ============================================================
# CONFIGURAÇÃO DA PÁGINA
# ============================================================

st.set_page_config(
    page_title="Desafio dos Sólidos 3D",
    page_icon="🔷",
    layout="centered"
)

# ============================================================
# ESTILO
# ============================================================

st.markdown("""
<style>

.main-title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
}

.subtitle {
    text-align: center;
    font-size: 20px;
}

.card {
    padding: 20px;
    border-radius: 15px;
    border: 2px solid #ddd;
    margin-bottom: 15px;
}

.question {
    font-size: 24px;
    font-weight: bold;
}

.correct {
    padding: 15px;
    border-radius: 10px;
    background-color: #d4edda;
    font-size: 18px;
}

.incorrect {
    padding: 15px;
    border-radius: 10px;
    background-color: #f8d7da;
    font-size: 18px;
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# FUNÇÕES MATEMÁTICAS
# ============================================================

def area_base_regular(n, lado):
    """
    Área de um polígono regular.
    """
    return (n * lado ** 2) / (4 * math.tan(math.pi / n))


def perimetro_base(n, lado):
    return n * lado


def apotema_base(n, lado):
    """
    Apótema do polígono regular da base.
    """
    return lado / (2 * math.tan(math.pi / n))


def elementos_prisma(n):
    vertices = 2 * n
    arestas = 3 * n
    faces = n + 2

    return vertices, arestas, faces


def elementos_piramide(n):
    vertices = n + 1
    arestas = 2 * n
    faces = n + 1

    return vertices, arestas, faces


def dados_prisma(n, lado, altura):

    Ab = area_base_regular(n, lado)
    Pb = perimetro_base(n, lado)

    Al = Pb * altura
    At = 2 * Ab + Al
    volume = Ab * altura

    vertices, arestas, faces = elementos_prisma(n)

    return {
        "Área da base": Ab,
        "Área lateral": Al,
        "Área total": At,
        "Volume": volume,
        "Vértices": vertices,
        "Arestas": arestas,
        "Faces": faces
    }


def dados_piramide(n, lado, altura):

    Ab = area_base_regular(n, lado)
    Pb = perimetro_base(n, lado)

    ap_base = apotema_base(n, lado)

    # Apótema lateral da pirâmide
    ap_lateral = math.sqrt(altura ** 2 + ap_base ** 2)

    Al = (Pb * ap_lateral) / 2
    At = Ab + Al
    volume = (Ab * altura) / 3

    vertices, arestas, faces = elementos_piramide(n)

    return {
        "Área da base": Ab,
        "Área lateral": Al,
        "Área total": At,
        "Volume": volume,
        "Vértices": vertices,
        "Arestas": arestas,
        "Faces": faces,
        "Apótema lateral": ap_lateral
    }


# ============================================================
# INICIALIZAÇÃO DO JOGO
# ============================================================

if "score" not in st.session_state:
    st.session_state.score = 0

if "question" not in st.session_state:
    st.session_state.question = 1

if "answered" not in st.session_state:
    st.session_state.answered = False

if "correct_answer" not in st.session_state:
    st.session_state.correct_answer = None

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "total_questions" not in st.session_state:
    st.session_state.total_questions = 10


# ============================================================
# FUNÇÃO PARA REINICIAR
# ============================================================

def reiniciar_jogo():

    st.session_state.score = 0
    st.session_state.question = 1
    st.session_state.answered = False
    st.session_state.correct_answer = None
    st.session_state.feedback = ""

    if "generated_question" in st.session_state:
        del st.session_state.generated_question


# ============================================================
# TÍTULO
# ============================================================

st.markdown(
    '<div class="main-title">🔷 DESAFIO DOS SÓLIDOS 3D 🔺</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Prismas e Pirâmides</div>',
    unsafe_allow_html=True
)

st.write("")

# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("⚙️ Configurações")

nivel = st.sidebar.selectbox(
    "Escolha o nível:",
    ["Fácil 🟢", "Médio 🟡", "Difícil 🔴"]
)

tipo = st.sidebar.selectbox(
    "Escolha o sólido:",
    ["Prisma 🔷", "Pirâmide 🔺", "Misturado 🎲"]
)

st.sidebar.markdown("---")

st.sidebar.write("### 📚 Conteúdos")

st.sidebar.write("🔹 Vértices")
st.sidebar.write("🔹 Arestas")
st.sidebar.write("🔹 Faces")
st.sidebar.write("🔹 Área da base")
st.sidebar.write("🔹 Área lateral")
st.sidebar.write("🔹 Área total")
st.sidebar.write("🔹 Volume")

st.sidebar.markdown("---")

if st.sidebar.button("🔄 Reiniciar Jogo"):
    reiniciar_jogo()
    st.rerun()


# ============================================================
# DIFICULDADE
# ============================================================

if nivel == "Fácil 🟢":

    lados_disponiveis = [3, 4, 5]
    alturas_disponiveis = [4, 5, 6]
    medidas_disponiveis = [2, 3, 4]

elif nivel == "Médio 🟡":

    lados_disponiveis = [4, 5, 6]
    alturas_disponiveis = [5, 6, 8]
    medidas_disponiveis = [3, 4, 5]

else:

    lados_disponiveis = [5, 6, 8]
    alturas_disponiveis = [7, 8, 10]
    medidas_disponiveis = [4, 5, 6]


# ============================================================
# GERAR QUESTÃO
# ============================================================

def gerar_questao():

    n = random.choice(lados_disponiveis)
    lado = random.choice(medidas_disponiveis)
    altura = random.choice(alturas_disponiveis)

    if tipo == "Misturado 🎲":
        solido = random.choice(["Prisma 🔷", "Pirâmide 🔺"])
    else:
        solido = tipo

    if solido == "Prisma 🔷":

        dados = dados_prisma(n, lado, altura)

    else:

        dados = dados_piramide(n, lado, altura)

    categorias = [
        "Vértices",
        "Arestas",
        "Faces",
        "Área da base",
        "Área lateral",
        "Área total",
        "Volume"
    ]

    categoria = random.choice(categorias)

    resposta = dados[categoria]

    # ========================================================
    # FORMATAÇÃO DA RESPOSTA
    # ========================================================

    if categoria in ["Vértices", "Arestas", "Faces"]:

        resposta_exata = int(resposta)

        unidade = ""

    else:

        resposta_exata = round(resposta, 2)

        if categoria == "Volume":
            unidade = " unidades³"
        else:
            unidade = " unidades²"

    # ========================================================
    # CRIAR ALTERNATIVAS
    # ========================================================

    alternativas = {resposta_exata}

    while len(alternativas) < 4:

        if categoria in ["Vértices", "Arestas", "Faces"]:

            erro = random.randint(1, 5)

            nova = resposta_exata + random.choice([-erro, erro])

            if nova > 0:
                alternativas.add(nova)

        else:

            erro_percentual = random.choice(
                [-0.30, -0.20, 0.20, 0.30]
            )

            nova = round(
                resposta_exata * (1 + erro_percentual),
                2
            )

            if nova > 0:
                alternativas.add(nova)

    alternativas = list(alternativas)
    random.shuffle(alternativas)

    return {
        "n": n,
        "lado": lado,
        "altura": altura,
        "solido": solido,
        "categoria": categoria,
        "resposta": resposta_exata,
        "alternativas": alternativas,
        "unidade": unidade
    }


# ============================================================
# CRIAR NOVA QUESTÃO
# ============================================================

if "generated_question" not in st.session_state:

    st.session_state.generated_question = gerar_questao()


q = st.session_state.generated_question


# ============================================================
# STATUS DO JOGO
# ============================================================

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "⭐ Pontos",
        st.session_state.score
    )

with col2:
    st.metric(
        "📝 Questão",
        f"{st.session_state.question}/10"
    )

with col3:
    if st.session_state.score >= 80:
        nivel_jogador = "🏆 Excelente"
    elif st.session_state.score >= 50:
        nivel_jogador = "👏 Bom"
    else:
        nivel_jogador = "💪 Continue"

    st.metric(
        "🏅 Desempenho",
        nivel_jogador
    )


progress = (
    st.session_state.question - 1
) / st.session_state.total_questions

st.progress(progress)


# ============================================================
# REPRESENTAÇÃO DO SÓLIDO
# ============================================================

st.markdown("---")

if q["solido"] == "Prisma 🔷":

    st.markdown("""
    <div style='text-align:center;font-size:90px;'>
    🔷
    </div>
    """, unsafe_allow_html=True)

else:

    st.markdown("""
    <div style='text-align:center;font-size:90px;'>
    🔺
    </div>
    """, unsafe_allow_html=True)


st.markdown(
    f"<h2 style='text-align:center'>{q['solido']}</h2>",
    unsafe_allow_html=True
)


# ============================================================
# INFORMAÇÕES DO SÓLIDO
# ============================================================

st.info(
    f"📐 Base: polígono regular com **{q['n']} lados**  \n"
    f"📏 Lado da base: **{q['lado']} unidades**  \n"
    f"📦 Altura: **{q['altura']} unidades**"
)


# ============================================================
# QUESTÃO
# ============================================================

st.markdown(
    f"""
    <div class='card'>
    <div class='question'>
    ❓ {q['categoria']}
    </div>
    <br>
    Qual é o valor correto?
    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# ALTERNATIVAS
# ============================================================

opcoes = []

for alternativa in q["alternativas"]:

    if q["categoria"] in [
        "Vértices",
        "Arestas",
        "Faces"
    ]:

        texto = f"{int(alternativa)}"

    else:

        texto = f"{alternativa:.2f}{q['unidade']}"

    opcoes.append(texto)


resposta_escolhida = st.radio(
    "Escolha uma resposta:",
    opcoes,
    key=f"resposta_{st.session_state.question}"
)


# ============================================================
# BOTÃO RESPONDER
# ============================================================

if st.button(
    "✅ RESPONDER",
    use_container_width=True
):

    valor_escolhido = float(
        resposta_escolhida.replace(
            " unidades³", ""
        ).replace(
            " unidades²", ""
        )
    )

    if valor_escolhido == q["resposta"]:

        st.session_state.score += 10

        st.session_state.feedback = "correct"

        st.session_state.answered = True

    else:

        st.session_state.feedback = "incorrect"

        st.session_state.answered = True

    st.rerun()


# ============================================================
# FEEDBACK
# ============================================================

if st.session_state.answered:

    if st.session_state.feedback == "correct":

        st.success(
            f"🎉 Excelente! A resposta **{q['resposta']}{q['unidade']}** está correta!"
        )

    else:

        st.error(
            f"❌ Não foi desta vez. A resposta correta é "
            f"**{q['resposta']}{q['unidade']}**."
        )

    # ========================================================
    # EXPLICAÇÃO
    # ========================================================

    st.markdown("### 💡 Explicação")

    if q["solido"] == "Prisma 🔷":

        dados = dados_prisma(
            q["n"],
            q["lado"],
            q["altura"]
        )

    else:

        dados = dados_piramide(
            q["n"],
            q["lado"],
            q["altura"]
        )

    if q["categoria"] == "Vértices":

        st.write(
            f"Para um {q['solido']}, com uma base de "
            f"{q['n']} lados:"
        )

        if q["solido"] == "Prisma 🔷":
            st.latex(
                f"V = 2 \\times {q['n']} = {dados['Vértices']}"
            )
        else:
            st.latex(
                f"V = {q['n']} + 1 = {dados['Vértices']}"
            )

    elif q["categoria"] == "Arestas":

        if q["solido"] == "Prisma 🔷":

            st.latex(
                f"A = 3 \\times {q['n']} = {dados['Arestas']}"
            )

        else:

            st.latex(
                f"A = 2 \\times {q['n']} = {dados['Arestas']}"
            )

    elif q["categoria"] == "Faces":

        if q["solido"] == "Prisma 🔷":

            st.latex(
                f"F = {q['n']} + 2 = {dados['Faces']}"
            )

        else:

            st.latex(
                f"F = {q['n']} + 1 = {dados['Faces']}"
            )

    elif q["categoria"] == "Área da base":

        st.write(
            "A base é um polígono regular."
        )

        st.latex(
            r"A_b = \frac{n \times a^2}"
            r"{4\tan(\pi/n)}"
        )

        st.write(
            f"Área da base ≈ {dados['Área da base']:.2f} unidades²"
        )

    elif q["categoria"] == "Área lateral":

        if q["solido"] == "Prisma 🔷":

            st.latex(
                r"A_L = P_b \times h"
            )

            st.write(
                f"Aₗ = {q['n']} × {q['lado']} × "
                f"{q['altura']}"
            )

        else:

            st.latex(
                r"A_L = \frac{P_b \times ap}{2}"
            )

            st.write(
                f"Apótema lateral ≈ "
                f"{dados['Apótema lateral']:.2f}"
            )

        st.write(
            f"Área lateral ≈ "
            f"{dados['Área lateral']:.2f} unidades²"
        )

    elif q["categoria"] == "Área total":

        if q["solido"] == "Prisma 🔷":

            st.latex(
                r"A_T = 2A_b + A_L"
            )

        else:

            st.latex(
                r"A_T = A_b + A_L"
            )

        st.write(
            f"Área total ≈ "
            f"{dados['Área total']:.2f} unidades²"
        )

    elif q["categoria"] == "Volume":

        if q["solido"] == "Prisma 🔷":

            st.latex(
                r"V = A_b \times h"
            )

        else:

            st.latex(
                r"V = \frac{A_b \times h}{3}"
            )

        st.write(
            f"Volume ≈ "
            f"{dados['Volume']:.2f} unidades³"
        )

    # ========================================================
    # PRÓXIMA QUESTÃO
    # ========================================================

    if st.session_state.question < 10:

        if st.button(
            "➡️ PRÓXIMA QUESTÃO",
            use_container_width=True
        ):

            st.session_state.question += 1
            st.session_state.answered = False
            st.session_state.feedback = ""
            st.session_state.generated_question = gerar_questao()

            st.rerun()

    else:

        st.markdown("---")

        st.balloons()

        st.success(
            f"🏆 JOGO TERMINADO! "
            f"Você conseguiu **{st.session_state.score} pontos de 100**!"
        )

        if st.session_state.score == 100:

            st.markdown(
                "### 🥇 PERFEITO! Você é um Mestre dos Sólidos 3D! 🔷🔺"
            )

        elif st.session_state.score >= 70:

            st.markdown(
                "### 🥈 Muito bom! Você domina muito bem os sólidos! 👏"
            )

        elif st.session_state.score >= 50:

            st.markdown(
                "### 🥉 Bom trabalho! Continue praticando! 💪"
            )

        else:

            st.markdown(
                "### 📚 Continue estudando. Você vai conseguir! 🚀"
            )

        if st.button(
            "🔄 JOGAR NOVAMENTE",
            use_container_width=True
        ):

            reiniciar_jogo()
            st.rerun()


# ============================================================
# RODAPÉ
# ============================================================

st.markdown("---")

st.markdown(
    """
    <div style='text-align:center'>
    <b>🔷 Desafio dos Sólidos 3D 🔺</b><br>
    Aprender Matemática através de desafios!
    </div>
    """,
    unsafe_allow_html=True
)