# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Six7R5rsOSBkCIMzaNFC23rb5paWZqRP
"""

import streamlit as st
import random

# --------------------------------------------------
# CONFIGURAÇÃO DA PÁGINA
# --------------------------------------------------
st.set_page_config(
    page_title="Aventura da Adição 🧮",
    page_icon="🍎",
    layout="centered"
)

# --------------------------------------------------
# ESTILO
# --------------------------------------------------
st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #FFF8E7, #E8F8FF);
    }

    .titulo {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        margin-bottom: 5px;
    }

    .subtitulo {
        text-align: center;
        font-size: 20px;
        margin-bottom: 25px;
    }

    .caixa {
        padding: 20px;
        border-radius: 20px;
        background-color: white;
        box-shadow: 0px 4px 15px rgba(0,0,0,0.1);
        text-align: center;
        margin: 15px 0;
    }

    .pergunta {
        font-size: 38px;
        font-weight: bold;
        text-align: center;
        padding: 20px;
    }

    .pontuacao {
        font-size: 25px;
        font-weight: bold;
        text-align: center;
    }
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# INICIALIZAR JOGO
# --------------------------------------------------
if "iniciado" not in st.session_state:
    st.session_state.iniciado = False

if "questao" not in st.session_state:
    st.session_state.questao = 0

if "pontuacao" not in st.session_state:
    st.session_state.pontuacao = 0

if "respondida" not in st.session_state:
    st.session_state.respondida = False

if "mensagem" not in st.session_state:
    st.session_state.mensagem = ""

if "nivel" not in st.session_state:
    st.session_state.nivel = "Fácil"

if "num1" not in st.session_state:
    st.session_state.num1 = 2

if "num2" not in st.session_state:
    st.session_state.num2 = 3

if "opcoes" not in st.session_state:
    st.session_state.opcoes = []

# --------------------------------------------------
# FUNÇÃO PARA NOVA PERGUNTA
# --------------------------------------------------
def nova_pergunta():
    nivel = st.session_state.nivel

    if nivel == "Fácil":
        a = random.randint(0, 5)
        b = random.randint(0, 5)

    elif nivel == "Médio":
        a = random.randint(1, 10)
        b = random.randint(1, 10)

    else:
        a = random.randint(5, 20)
        b = random.randint(5, 20)

    resposta = a + b

    opcoes = {resposta}

    while len(opcoes) < 4:
        erro = resposta + random.randint(-5, 5)
        if erro >= 0:
            opcoes.add(erro)

    st.session_state.num1 = a
    st.session_state.num2 = b
    st.session_state.opcoes = list(opcoes)
    random.shuffle(st.session_state.opcoes)
    st.session_state.respondida = False
    st.session_state.mensagem = ""

# --------------------------------------------------
# TÍTULO
# --------------------------------------------------
st.markdown(
    '<div class="titulo">🍎 AVENTURA DA ADIÇÃO 🍎</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitulo">🎮 Aprende a somar enquanto te divertes!</div>',
    unsafe_allow_html=True
)

# --------------------------------------------------
# MENU
# --------------------------------------------------
if not st.session_state.iniciado:

    st.markdown("""
    <div class="caixa">
        <h2>🌟 Bem-vindo, pequeno matemático! 🌟</h2>
        <p>
        Resolve as contas de adição, ganha pontos
        e torna-te um verdadeiro campeão da matemática! 🏆
        </p>
    </div>
    """, unsafe_allow_html=True)

    nivel = st.selectbox(
        "🎯 Escolhe o nível:",
        ["Fácil", "Médio", "Difícil"]
    )

    st.session_state.nivel = nivel

    if st.button("🚀 COMEÇAR O JOGO", use_container_width=True):

        st.session_state.iniciado = True
        st.session_state.questao = 1
        st.session_state.pontuacao = 0

        nova_pergunta()

        st.rerun()

# --------------------------------------------------
# JOGO
# --------------------------------------------------
else:

    total_questoes = 10

    # Cabeçalho
    col1, col2 = st.columns(2)

    with col1:
        st.markdown(
            f"### 📝 Pergunta {st.session_state.questao}/{total_questoes}"
        )

    with col2:
        st.markdown(
            f"### ⭐ Pontos: {st.session_state.pontuacao}"
        )

    # Barra de progresso
    progresso = (st.session_state.questao - 1) / total_questoes
    st.progress(progresso)

    # Pergunta
    st.markdown(
        f"""
        <div class="pergunta">
        🍎 {st.session_state.num1} + {st.session_state.num2} = ?
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("### 👇 Escolhe a resposta correta:")

    # Opções
    col1, col2 = st.columns(2)

    for i, opcao in enumerate(st.session_state.opcoes):

        if i % 2 == 0:
            coluna = col1
        else:
            coluna = col2

        with coluna:

            if st.button(
                f"🍎 {opcao}",
                key=f"opcao_{st.session_state.questao}_{i}",
                use_container_width=True,
                disabled=st.session_state.respondida
            ):

                resposta_correta = (
                    st.session_state.num1 +
                    st.session_state.num2
                )

                st.session_state.respondida = True

                if opcao == resposta_correta:

                    st.session_state.pontuacao += 10
                    st.session_state.mensagem = (
                        "🎉 Muito bem! Resposta correta! ⭐"
                    )

                else:

                    st.session_state.mensagem = (
                        f"😊 Quase! A resposta correta é "
                        f"{resposta_correta}."
                    )

                st.rerun()

    # Feedback
    if st.session_state.respondida:

        st.info(st.session_state.mensagem)

        if st.session_state.questao < total_questoes:

            if st.button(
                "➡️ PRÓXIMA PERGUNTA",
                use_container_width=True
            ):

                st.session_state.questao += 1
                nova_pergunta()

                st.rerun()

        else:

            st.balloons()

            st.markdown(
                f"""
                <div class="caixa">
                    <h1>🏆 FIM DO JOGO! 🏆</h1>
                    <h2>⭐ Pontuação:
                    {st.session_state.pontuacao}/100</h2>
                </div>
                """,
                unsafe_allow_html=True
            )

            if st.session_state.pontuacao >= 90:
                st.success("🌟 Excelente! És um campeão da adição!")

            elif st.session_state.pontuacao >= 70:
                st.success("👏 Muito bom! Continua a praticar!")

            elif st.session_state.pontuacao >= 50:
                st.info("😊 Bom trabalho! Podes melhorar ainda mais!")

            else:
                st.warning(
                    "💪 Continua a praticar. Tu consegues!"
                )

            if st.button(
                "🔄 JOGAR NOVAMENTE",
                use_container_width=True
            ):

                st.session_state.iniciado = False
                st.session_state.questao = 0
                st.session_state.pontuacao = 0
                st.session_state.respondida = False

                st.rerun()